<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ElemenKompetensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('elemen_kompetensi')->insert([
            ['id_elemen' => 1, 'id_unit' => 1, 'nama_elemen' => 'Mengidentifikasi elemen desain'],
            ['id_elemen' => 2, 'id_unit' => 1, 'nama_elemen' => 'Merencanakan proses produksi aset visual multimedia'],
            ['id_elemen' => 3, 'id_unit' => 2, 'nama_elemen' => 'Memproduksi aset visual multimedia'],
            ['id_elemen' => 4, 'id_unit' => 2, 'nama_elemen' => 'Mereview hasil desain'],
            ['id_elemen' => 5, 'id_unit' => 3, 'nama_elemen' => 'Menyusun teknis pengelolaan konten'],
            ['id_elemen' => 6, 'id_unit' => 3, 'nama_elemen' => 'Membuat strategi pencarian'],
            ['id_elemen' => 7, 'id_unit' => 4, 'nama_elemen' => 'Membuat basis data perangkat multimedia'],
            ['id_elemen' => 8, 'id_unit' => 4, 'nama_elemen' => 'Menyelesaikan masalah yang dihadapi'],
            ['id_elemen' => 9, 'id_unit' => 5, 'nama_elemen' => 'Mengkonfirmasi prosedur distribusi asset'],
            ['id_elemen' => 10, 'id_unit' => 5, 'nama_elemen' => 'Memastikan distributsi asset standar industri'],
            ['id_elemen' => 11, 'id_unit' => 6, 'nama_elemen' => 'Membuat daftar teknologi dan perangkat jaringan saat ini (existing)'],
            ['id_elemen' => 12, 'id_unit' => 6, 'nama_elemen' => 'Membuat daftar teknologi yang dapat memperbaiki kinerja jaringan'],
            ['id_elemen' => 13, 'id_unit' => 7, 'nama_elemen' => 'Menentukan kebutuhan pengguna secara keseluruhan'],
            ['id_elemen' => 14, 'id_unit' => 7, 'nama_elemen' => 'Membuat spesifikasi topologi jaringan'],
            ['id_elemen' => 15, 'id_unit' => 8, 'nama_elemen' => 'Mengidentifikasi sistem operasi pada jaringan'],
            ['id_elemen' => 16, 'id_unit' => 8, 'nama_elemen' => 'Membagi alamat jaringan pada perangkat jaringan'],
            ['id_elemen' => 17, 'id_unit' => 8, 'nama_elemen' => 'Mendokumentasikan pengalamatan jaringan'],
            ['id_elemen' => 18, 'id_unit' => 9, 'nama_elemen' => 'Mempersiapkan peralatan dan bahan/materi yang diperlukan'],
            ['id_elemen' => 19, 'id_unit' => 9, 'nama_elemen' => 'Mengumpulkan informasi mengenai perangkat jaringan yang ada di pasaran'],
            ['id_elemen' => 20, 'id_unit' => 9, 'nama_elemen' => 'Menuliskan spesifikasi perangkat jaringan untuk keperluan pengguna'],
            ['id_elemen' => 21, 'id_unit' => 10, 'nama_elemen' => 'Merencanakan pengkabelan horizontal'],
            ['id_elemen' => 22, 'id_unit' => 10, 'nama_elemen' => 'Menginstalasi pengkabelan horizontal'],
            ['id_elemen' => 23, 'id_unit' => 10, 'nama_elemen' => 'Membuat dokumentasi pengkabelan terstruktur horizontal'],
            ['id_elemen' => 24, 'id_unit' => 11, 'nama_elemen' => 'Mengidentifikasi konsep data dan struktur data'],
            ['id_elemen' => 25, 'id_unit' => 11, 'nama_elemen' => 'Menerapkan struktur data dan akses terhadap struktur data tersebut'],
            ['id_elemen' => 26, 'id_unit' => 12, 'nama_elemen' => 'Menggunakan metode pengembangan program'],
            ['id_elemen' => 27, 'id_unit' => 12, 'nama_elemen' => 'Menggunakan diagram program dan deskripsi program'],
            ['id_elemen' => 28, 'id_unit' => 12, 'nama_elemen' => 'Menerapkan hasil pemodelan ke dalam pengembangan program'],
            ['id_elemen' => 29, 'id_unit' => 13, 'nama_elemen' => 'Mengidentifikasi mekanisme running atau eksekusi source code'],
            ['id_elemen' => 30, 'id_unit' => 13, 'nama_elemen' => 'Mengeksekusi source code'],
            ['id_elemen' => 31, 'id_unit' => 13, 'nama_elemen' => 'Mengidentifikasi hasil eksekusi'],
            ['id_elemen' => 32, 'id_unit' => 14, 'nama_elemen' => 'Menerapkan codingguidelines dan best practices dalam penulisan program (kode sumber)'],
            ['id_elemen' => 33, 'id_unit' => 14, 'nama_elemen' => 'Menggunakan ukuran performansi dalam menuliskan kode sumber'],
            ['id_elemen' => 34, 'id_unit' => 15, 'nama_elemen' => 'Menggunakan tipe data dan control program'],
            ['id_elemen' => 35, 'id_unit' => 15, 'nama_elemen' => 'Membuat program sederhana'],
            ['id_elemen' => 36, 'id_unit' => 15, 'nama_elemen' => 'Membuat program menggunakan prosedur dan fungsi'],
            ['id_elemen' => 37, 'id_unit' => 15, 'nama_elemen' => 'Membuat program menggunakan array'],
            ['id_elemen' => 38, 'id_unit' => 15, 'nama_elemen' => 'Membuat program untuk akses file'],
            ['id_elemen' => 39, 'id_unit' => 15, 'nama_elemen' => 'Mengkompilasi Program'],
            ['id_elemen' => 40, 'id_unit' => 16, 'nama_elemen' => 'Melakukan identifikasi kode program'],
            ['id_elemen' => 41, 'id_unit' => 16, 'nama_elemen' => 'Membuat dokumentasi modul program'],
            ['id_elemen' => 42, 'id_unit' => 16, 'nama_elemen' => 'Membuat dokumentasi fungsi, prosedur atau method program'],
            ['id_elemen' => 43, 'id_unit' => 16, 'nama_elemen' => 'Men-generate dokumentasi'],
            ['id_elemen' => 44, 'id_unit' => 17, 'nama_elemen' => 'Mempersiapkan kode program'],
            ['id_elemen' => 45, 'id_unit' => 17, 'nama_elemen' => 'Melakukan debugging'],
            ['id_elemen' => 46, 'id_unit' => 17, 'nama_elemen' => 'Memperbaiki program'],
            ['id_elemen' => 47, 'id_unit' => 18, 'nama_elemen' => 'Menentukan kebutuhan uji coba dalam pengembangan'],
            ['id_elemen' => 48, 'id_unit' => 18, 'nama_elemen' => 'Mempersiapkan dokumentasi uji coba'],
            ['id_elemen' => 49, 'id_unit' => 18, 'nama_elemen' => 'Mempersiapkan data uji'],
            ['id_elemen' => 50, 'id_unit' => 18, 'nama_elemen' => 'Melaksanakan prosedur uji coba'],
            ['id_elemen' => 51, 'id_unit' => 18, 'nama_elemen' => 'Mengevaluasi hasil uji coba'],
            ['id_elemen' => 52, 'id_unit' => 19, 'nama_elemen' => 'Memproses pencatatan surat/dokumen termasuk surat elektronik yang masuk dan keluar'],
            ['id_elemen' => 53, 'id_unit' => 19, 'nama_elemen' => 'Mendistribusikan surat /dokumen'],
            ['id_elemen' => 54, 'id_unit' => 20, 'nama_elemen' => 'Menyiapkan dokumen'],
            ['id_elemen' => 55, 'id_unit' => 20, 'nama_elemen' => 'Mendesain dokumen'],
            ['id_elemen' => 56, 'id_unit' => 20, 'nama_elemen' => 'Memproduksi dokumen'],
            ['id_elemen' => 57, 'id_unit' => 21, 'nama_elemen' => 'Mengidentifikasi kegiatan pimpinan'],
            ['id_elemen' => 58, 'id_unit' => 21, 'nama_elemen' => 'Mengatur jadwal kegiatan pimpinan'],
            ['id_elemen' => 59, 'id_unit' => 21, 'nama_elemen' => 'Mencatat jadwal kegiatan pimpinan'],
            ['id_elemen' => 60, 'id_unit' => 22, 'nama_elemen' => 'Memproses undangan rapat/pertemuan'],
            ['id_elemen' => 61, 'id_unit' => 22, 'nama_elemen' => 'Mempersiapkan peralatan, perlengkapan dan tenaga ahli'],
            ['id_elemen' => 62, 'id_unit' => 22, 'nama_elemen' => 'Mengatur biaya pertemuan'],
            ['id_elemen' => 63, 'id_unit' => 22, 'nama_elemen' => 'Menyelenggarakan pertemuan'],
            ['id_elemen' => 64, 'id_unit' => 22, 'nama_elemen' => 'Membuat laporan pertemuan'],
            ['id_elemen' => 65, 'id_unit' => 23, 'nama_elemen' => 'Menjawab telepon'],
            ['id_elemen' => 66, 'id_unit' => 23, 'nama_elemen' => 'Melakukan panggilan telepon'],
            ['id_elemen' => 67, 'id_unit' => 23, 'nama_elemen' => 'Menangani pesan'],
            ['id_elemen' => 68, 'id_unit' => 24, 'nama_elemen' => 'Menyiapkan komunikasi'],
            ['id_elemen' => 69, 'id_unit' => 24, 'nama_elemen' => 'Melakukan kontak dengan komunikan'],
            ['id_elemen' => 70, 'id_unit' => 24, 'nama_elemen' => 'Memproses informasi'],
            ['id_elemen' => 71, 'id_unit' => 25, 'nama_elemen' => 'Melakukan komunikasi seharihari di tempat kerja'],
            ['id_elemen' => 72, 'id_unit' => 25, 'nama_elemen' => 'Menggunakan kalimat sesuai SOP organisasi'],
            ['id_elemen' => 73, 'id_unit' => 25, 'nama_elemen' => 'Melakukan komunikasi melalui telepon'],
            ['id_elemen' => 74, 'id_unit' => 26, 'nama_elemen' => 'Mengenali tanda-tanda umum yang biasa digunakan pada Industri'],
            ['id_elemen' => 75, 'id_unit' => 26, 'nama_elemen' => 'Membaca dokumen kerja sederhana'],
            ['id_elemen' => 76, 'id_unit' => 26, 'nama_elemen' => 'Membaca teks instruksional sederhana'],
            ['id_elemen' => 77, 'id_unit' => 27, 'nama_elemen' => 'Mengidentifikasi tujuan penulisan'],
            ['id_elemen' => 78, 'id_unit' => 27, 'nama_elemen' => 'Memperhatikan kalimat pada penulisan'],
            ['id_elemen' => 79, 'id_unit' => 28, 'nama_elemen' => 'Menerapkan konsep pelayanan prima dan prinsip-prinsip pelayanan'],
            ['id_elemen' => 80, 'id_unit' => 28, 'nama_elemen' => 'Menerapkan unsurunsur kualitas pelayanan prima'],
            ['id_elemen' => 81, 'id_unit' => 28, 'nama_elemen' => 'Memberikan pelayanan kepada pelanggan'],
            ['id_elemen' => 82, 'id_unit' => 29, 'nama_elemen' => 'Mempersiapkan peralatan'],
            ['id_elemen' => 83, 'id_unit' => 29, 'nama_elemen' => 'Membuat dokumen dari konsep atau teks langsung'],
            ['id_elemen' => 84, 'id_unit' => 29, 'nama_elemen' => 'Menyimpan Dokumen'],
            ['id_elemen' => 85, 'id_unit' => 29, 'nama_elemen' => 'Mencetak Dokumen'],
            ['id_elemen' => 86, 'id_unit' => 30, 'nama_elemen' => 'Mengidentifikasi jenis peralatan komunikasi'],
            ['id_elemen' => 87, 'id_unit' => 30, 'nama_elemen' => 'Menggunakan peralatan komunikasi'],
            ['id_elemen' => 88, 'id_unit' => 31, 'nama_elemen' => 'Mengakses aplikasi piranti lunak'],
            ['id_elemen' => 89, 'id_unit' => 31, 'nama_elemen' => 'Melakukan pengoperasian aplikasi piranti lunak'],
            ['id_elemen' => 90, 'id_unit' => 32, 'nama_elemen' => 'Membuka file'],
            ['id_elemen' => 91, 'id_unit' => 32, 'nama_elemen' => 'Mengunduh data'],
            ['id_elemen' => 92, 'id_unit' => 33, 'nama_elemen' => 'Memilih peralatan dan sumber daya kerja'],
            ['id_elemen' => 93, 'id_unit' => 33, 'nama_elemen' => 'Mengoperasikan peralatan'],
            ['id_elemen' => 94, 'id_unit' => 33, 'nama_elemen' => 'Memelihara peralatan atau sumber daya kerja'],
            ['id_elemen' => 95, 'id_unit' => 34, 'nama_elemen' => 'Mempersiapkan piranti lunak'],
            ['id_elemen' => 96, 'id_unit' => 34, 'nama_elemen' => 'Mengenali menu, format alamat email dan konfigurasi sederhana'],
            ['id_elemen' => 97, 'id_unit' => 34, 'nama_elemen' => 'Membuat, membaca, membuat dan mengirim surat/dokumen elektronik'],
            ['id_elemen' => 98, 'id_unit' => 34, 'nama_elemen' => 'Menyimpan surat/dokumen elektronik'],
            ['id_elemen' => 99, 'id_unit' => 35, 'nama_elemen' => 'Menyiapkan Perangkat komputer dan informasi yang dibutuhkan'],
            ['id_elemen' => 100, 'id_unit' => 35, 'nama_elemen' => 'Membuka homepage'],
            ['id_elemen' => 101, 'id_unit' => 35, 'nama_elemen' => 'Mengakses data/informasi'],
            ['id_elemen' => 102, 'id_unit' => 36, 'nama_elemen' => 'Mengenali produk perbankan'],
            ['id_elemen' => 103, 'id_unit' => 36, 'nama_elemen' => 'Melakukan transaksi perbankan'],
            ['id_elemen' => 104, 'id_unit' => 36, 'nama_elemen' => 'Mencatat dan menyimpan buktibukti transaksi perbankan yang sudah dilakukan'],
            ['id_elemen' => 105, 'id_unit' => 37, 'nama_elemen' => 'Melakukan penyimpanan dokumen/surat'],
            ['id_elemen' => 106, 'id_unit' => 37, 'nama_elemen' => 'Menjaga sistem kearsipan manual maupun elektronik'],
            ['id_elemen' => 107, 'id_unit' => 37, 'nama_elemen' => 'Melakukan pengendalian dokumen'],
            ['id_elemen' => 108, 'id_unit' => 38, 'nama_elemen' => 'Menjaga keamanan peralatan dan tempat kerja'],
            ['id_elemen' => 109, 'id_unit' => 38, 'nama_elemen' => 'Menjaga kebersihan peralatan dan tempat kerja'],
            ['id_elemen' => 110, 'id_unit' => 38, 'nama_elemen' => 'Mengatasi situasi-situasi darurat'],
            ['id_elemen' => 111, 'id_unit' => 38, 'nama_elemen' => 'Menangani tindakan pertolongan pertama pada kecelakaan di kantor'],
            ['id_elemen' => 112, 'id_unit' => 39, 'nama_elemen' => 'Menggunakan sistem keamanan penyimpanan secara rutin'],
            ['id_elemen' => 113, 'id_unit' => 39, 'nama_elemen' => 'Meminimalisir pencurian'],
            ['id_elemen' => 114, 'id_unit' => 40, 'nama_elemen' => 'Mengatur area kerja'],
            ['id_elemen' => 115, 'id_unit' => 40, 'nama_elemen' => 'Membersihkan area kerja'],
            ['id_elemen' => 116, 'id_unit' => 40, 'nama_elemen' => 'Menangani potensi bahaya sederhana'],
            ['id_elemen' => 117, 'id_unit' => 41, 'nama_elemen' => 'Mengidentifikasi tugas dan tanggung jawab kerja pribadi'],
            ['id_elemen' => 118, 'id_unit' => 41, 'nama_elemen' => 'Menyusun urutan tugas sesuai dengan jadwal kerja'],
            ['id_elemen' => 119, 'id_unit' => 41, 'nama_elemen' => 'Mendiskusikan perubahan tugas dan tanggung jawab kepada atasan'],
            ['id_elemen' => 120, 'id_unit' => 42, 'nama_elemen' => 'Mengindetifikasi kegunaan peralatan ritel'],
            ['id_elemen' => 121, 'id_unit' => 42, 'nama_elemen' => 'Memakai peralatan ritel sesuai dengan anjuran produsen'],
            ['id_elemen' => 122, 'id_unit' => 42, 'nama_elemen' => 'Memelihara peralatan sesuai dengan anjuran produsen'],
            ['id_elemen' => 123, 'id_unit' => 43, 'nama_elemen' => 'Melakukan pekerjaan sesuai persyaratan perusahaan'],
            ['id_elemen' => 124, 'id_unit' => 43, 'nama_elemen' => 'Mendukung tim kerja'],
            ['id_elemen' => 125, 'id_unit' => 43, 'nama_elemen' => 'Menjaga penampilan pribadi'],
            ['id_elemen' => 126, 'id_unit' => 43, 'nama_elemen' => 'Mengembangkan kebiasaan kerja yang efektif'],
            ['id_elemen' => 127, 'id_unit' => 44, 'nama_elemen' => 'Melakukan komunikasi tatap muka dengan pelanggan and rekan kerja'],
            ['id_elemen' => 128, 'id_unit' => 44, 'nama_elemen' => 'Menggunakan teknologi untuk berkomunikasi dengan pelanggan and rekan kerja'],
            ['id_elemen' => 129, 'id_unit' => 44, 'nama_elemen' => 'Melakukan komunikasi dengan pelanggan and rekan kerja dari latar belakang yang berbeda-beda'],
            ['id_elemen' => 130, 'id_unit' => 44, 'nama_elemen' => 'Bekerja dalam tim'],
            ['id_elemen' => 131, 'id_unit' => 44, 'nama_elemen' => 'Menafsirkan dokumen ritel'],
            ['id_elemen' => 132, 'id_unit' => 45, 'nama_elemen' => 'Menerapkan prosedur keselamatan dasar'],
            ['id_elemen' => 133, 'id_unit' => 45, 'nama_elemen' => 'Menerapkan prosedur darurat dasar'],
            ['id_elemen' => 134, 'id_unit' => 46, 'nama_elemen' => 'Mengemas produk'],
            ['id_elemen' => 135, 'id_unit' => 46, 'nama_elemen' => 'Memberi label pada produk yang telah dikemas'],
            ['id_elemen' => 136, 'id_unit' => 47, 'nama_elemen' => 'Menyiapkan keperluan untuk stocktaking'],
            ['id_elemen' => 137, 'id_unit' => 47, 'nama_elemen' => 'Melakukan stocktaking'],
            ['id_elemen' => 138, 'id_unit' => 47, 'nama_elemen' => 'Mengidentifikasi perbedaan dan selisih'],
            ['id_elemen' => 139, 'id_unit' => 47, 'nama_elemen' => 'Melengkapi dokumentasi'],
            ['id_elemen' => 140, 'id_unit' => 48, 'nama_elemen' => 'Mengidentifikasi keperluan untuk display'],
            ['id_elemen' => 141, 'id_unit' => 48, 'nama_elemen' => 'Mengembangkan ideide untuk display'],
            ['id_elemen' => 142, 'id_unit' => 48, 'nama_elemen' => 'Merencanakan and membuat display'],
            ['id_elemen' => 143, 'id_unit' => 48, 'nama_elemen' => 'Menjaga bentuk dan penataan display'],
            ['id_elemen' => 144, 'id_unit' => 49, 'nama_elemen' => 'Mengidentifikasi luas, sektor dan tanggung jawab industri'],
            ['id_elemen' => 145, 'id_unit' => 49, 'nama_elemen' => 'Menerapkan pedoman, prosedur, dan aturan'],
            ['id_elemen' => 146, 'id_unit' => 49, 'nama_elemen' => 'Mengelola informasi'],
            ['id_elemen' => 147, 'id_unit' => 49, 'nama_elemen' => 'Merencanakan penyelesaian pekerjaan dengan mempertimbangkan keterbatasan waktu dan sumber daya'],
            ['id_elemen' => 148, 'id_unit' => 49, 'nama_elemen' => 'Merancang dan mengelola kompetensi personal'],
            ['id_elemen' => 149, 'id_unit' => 50, 'nama_elemen' => 'Mengikuti prosedur kerja untuk mengidentifikasi bahaya dan pengendalian resiko'],
            ['id_elemen' => 150, 'id_unit' => 50, 'nama_elemen' => 'Berkontribusi dalam pengaturan manajemen K3'],
            ['id_elemen' => 151, 'id_unit' => 50, 'nama_elemen' => 'Menerapkan praktik-praktik K3'],
            ['id_elemen' => 152, 'id_unit' => 51, 'nama_elemen' => 'Memeriksa dokumen sumber dan dokumen pendukung'],
            ['id_elemen' => 153, 'id_unit' => 51, 'nama_elemen' => 'Mencatat dokumen sumber ke dalam jurnal'],
            ['id_elemen' => 154, 'id_unit' => 51, 'nama_elemen' => 'Mengarsipkan dokumen sumber dan pendukung'],
            ['id_elemen' => 155, 'id_unit' => 52, 'nama_elemen' => 'Mempersiapkan pengelolaan buku besar'],
            ['id_elemen' => 156, 'id_unit' => 52, 'nama_elemen' => 'Membukukan jumlah angka dari jurnal ke buku besar'],
            ['id_elemen' => 157, 'id_unit' => 52, 'nama_elemen' => 'Menyusun daftar saldo akun dalam buku besar'],
            ['id_elemen' => 158, 'id_unit' => 53, 'nama_elemen' => 'Mencatat jurnal penyesuaian'],
            ['id_elemen' => 159, 'id_unit' => 53, 'nama_elemen' => 'Menyajikan laporan'],
            ['id_elemen' => 160, 'id_unit' => 53, 'nama_elemen' => 'Mencatat jurnal penutup'],
            ['id_elemen' => 161, 'id_unit' => 53, 'nama_elemen' => 'Memposting jurnal penyesuaian dan jurnal penutup ke buku besar'],
            ['id_elemen' => 162, 'id_unit' => 54, 'nama_elemen' => 'Mempersiapkan komputer and paket program pengolah angka'],
            ['id_elemen' => 163, 'id_unit' => 54, 'nama_elemen' => 'Mengentry data'],
            ['id_elemen' => 164, 'id_unit' => 54, 'nama_elemen' => 'Mengolah data dengan fungsi-fungsi program pengolah angka'],
            ['id_elemen' => 165, 'id_unit' => 54, 'nama_elemen' => 'Membuat laporan'],
            ['id_elemen' => 166, 'id_unit' => 55, 'nama_elemen' => 'Menyiapkan data awal perusahaan'],
            ['id_elemen' => 167, 'id_unit' => 55, 'nama_elemen' => 'Menyusun data setup awal dan saldo awal'],
            ['id_elemen' => 168, 'id_unit' => 55, 'nama_elemen' => 'Melakukan entry transaksi'],
            ['id_elemen' => 169, 'id_unit' => 55, 'nama_elemen' => 'Mencetak laporan keuangan dan laporan lainnya'],
            ['id_elemen' => 170, 'id_unit' => 55, 'nama_elemen' => 'Membuat backup file'],
            ['id_elemen' => 171, 'id_unit' => 56, 'nama_elemen' => 'Melakukan survei teknis'],
            ['id_elemen' => 172, 'id_unit' => 56, 'nama_elemen' => 'Membuat daftar kebutuhan teknis pengguna jaringan'],
            ['id_elemen' => 173, 'id_unit' => 57, 'nama_elemen' => 'Membuat daftar teknologi dan perangkat jaringan saat ini (existing)'],
            ['id_elemen' => 174, 'id_unit' => 57, 'nama_elemen' => 'Membuat daftar teknologi yang dapat memperbaiki kinerja jaringan'],
            ['id_elemen' => 175, 'id_unit' => 58, 'nama_elemen' => 'Mempersiapkan peralatan dan bahan yang diperlukan'],
            ['id_elemen' => 176, 'id_unit' => 58, 'nama_elemen' => 'Memasang konektor pada kabel jaringan'],
            ['id_elemen' => 177, 'id_unit' => 58, 'nama_elemen' => 'Menguji koneksi kabel'],
            ['id_elemen' => 178, 'id_unit' => 59, 'nama_elemen' => 'Merencanakan pengkabelan horizontal'],
            ['id_elemen' => 179, 'id_unit' => 59, 'nama_elemen' => 'Menginstalasi pengkabelan horizontal'],
            ['id_elemen' => 180, 'id_unit' => 59, 'nama_elemen' => 'Membuat dokumentasi pengkabelan terstruktur horizontal'],
            ['id_elemen' => 181, 'id_unit' => 60, 'nama_elemen' => 'Mempersiapkan peralatan dan bahan/materi yang diperlukan'],
            ['id_elemen' => 182, 'id_unit' => 60, 'nama_elemen' => 'Mengumpulkan informasi mengenai perangkat jaringan yang ada di pasaran'],
            ['id_elemen' => 183, 'id_unit' => 60, 'nama_elemen' => 'Menuliskan spesifikasi perangkat jaringan untuk keperluan pengguna'],
            ['id_elemen' => 184, 'id_unit' => 61, 'nama_elemen' => 'Menentukan spesifikasi perangkat'],
            ['id_elemen' => 185, 'id_unit' => 61, 'nama_elemen' => 'Menginstalasi perangkat'],
            ['id_elemen' => 186, 'id_unit' => 61, 'nama_elemen' => 'Menguji perangkat'],
            ['id_elemen' => 187, 'id_unit' => 62, 'nama_elemen' => 'Menentukan kebutuhan pengguna secara keseluruhan'],
            ['id_elemen' => 188, 'id_unit' => 62, 'nama_elemen' => 'Membuat spesifikasi topologi jaringan'],
            ['id_elemen' => 189, 'id_unit' => 63, 'nama_elemen' => 'Mengidentifikasi sistem operasi pada jaringan'],
            ['id_elemen' => 190, 'id_unit' => 63, 'nama_elemen' => 'Membagi alamat jaringan pada perangkat jaringan'],
            ['id_elemen' => 191, 'id_unit' => 63, 'nama_elemen' => 'Mendokumentasikan pengalamatan jaringan'],
            ['id_elemen' => 192, 'id_unit' => 64, 'nama_elemen' => 'Menentukan spesifikasi switch'],
            ['id_elemen' => 193, 'id_unit' => 64, 'nama_elemen' => 'Memilih switch yang tepat'],
            ['id_elemen' => 194, 'id_unit' => 64, 'nama_elemen' => 'Memasang switch'],
            ['id_elemen' => 195, 'id_unit' => 64, 'nama_elemen' => 'Menguji switch pada jaringan'],
            ['id_elemen' => 196, 'id_unit' => 65, 'nama_elemen' => 'Menetapkan persyaratan perangkat jaringan dari pengguna'],
            ['id_elemen' => 197, 'id_unit' => 65, 'nama_elemen' => 'Menyiapkan perangkat jaringan'],
            ['id_elemen' => 198, 'id_unit' => 65, 'nama_elemen' => 'Meng-install perangkat keras jaringan'],
            ['id_elemen' => 199, 'id_unit' => 65, 'nama_elemen' => 'Menyediakan dukungan untuk produk-produk yang diinstal'],
            ['id_elemen' => 200, 'id_unit' => 66, 'nama_elemen' => 'Menyiapkan perangkat jaringan'],
            ['id_elemen' => 201, 'id_unit' => 66, 'nama_elemen' => 'Mengkonfigurasi router pada perangkat jaringan'],
            ['id_elemen' => 202, 'id_unit' => 66, 'nama_elemen' => 'Menguji routing pada perangkat jaringan'],
            ['id_elemen' => 203, 'id_unit' => 66, 'nama_elemen' => 'Mendokumentasikan konfigurasi routing'],
            ['id_elemen' => 204, 'id_unit' => 67, 'nama_elemen' => 'Mengidentifikasi dan memodifikasi akun pengguna agar selalu terkendali'],
            ['id_elemen' => 205, 'id_unit' => 67, 'nama_elemen' => 'Memastikan akses yang aman ke file dan sumber daya'],
            ['id_elemen' => 206, 'id_unit' => 67, 'nama_elemen' => 'Mengembangkan Service Level Agreement (Perjanjian Tingkat Layanan) atau SLA'],
            ['id_elemen' => 207, 'id_unit' => 68, 'nama_elemen' => 'Menyiapkan Data dokumentasi dari jaringan yang berjalan'],
            ['id_elemen' => 208, 'id_unit' => 68, 'nama_elemen' => 'Menganalisis kebutuhan secara physical'],
            ['id_elemen' => 209, 'id_unit' => 68, 'nama_elemen' => 'Mendokumentasi konfigurasi yang sedang beroperasi'],
            ['id_elemen' => 210, 'id_unit' => 68, 'nama_elemen' => 'Mengganti peralatan sesuai dengan konfigurasi sebelumnya']
        ]);
    }
}