<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('kuk')->insert([
            ['id_kuk' => 1, 'id_elemen' => 1, 'deskripsi_kuk' => 'Elemen-elemen desain diidentifikasi'],
            ['id_kuk' => 2, 'id_elemen' => 1, 'deskripsi_kuk' => 'Langkah kerja setiap kebutuhan elemen desain ditetapkan.'],
            ['id_kuk' => 3, 'id_elemen' => 2, 'deskripsi_kuk' => 'Prosedur pengerjaan asset visual diidentifikasi'],
            ['id_kuk' => 4, 'id_elemen' => 2, 'deskripsi_kuk' => 'Kebutuhan aset visual multimedia diidentifikasi.'],
            ['id_kuk' => 5, 'id_elemen' => 3, 'deskripsi_kuk' => 'Prosedur pengerjaan asset visual teridentifikasi'],
            ['id_kuk' => 6, 'id_elemen' => 3, 'deskripsi_kuk' => 'Aset visual multimedia di-produksi'],
            ['id_kuk' => 7, 'id_elemen' => 3, 'deskripsi_kuk' => 'Penyimpanan asset secara berkala dilakukan'],
            ['id_kuk' => 8, 'id_elemen' => 4, 'deskripsi_kuk' => 'Hasil kerja dievaluasi secara berkala'],
            ['id_kuk' => 9, 'id_elemen' => 4, 'deskripsi_kuk' => 'Tuntutan perbaikan visual dipersiapkan'],
            ['id_kuk' => 10, 'id_elemen' => 4, 'deskripsi_kuk' => 'Proses perbaikan dilakukan'],
            ['id_kuk' => 11, 'id_elemen' => 5, 'deskripsi_kuk' => 'Personil pengelola asset dikonfirmasi'],
            ['id_kuk' => 12, 'id_elemen' => 5, 'deskripsi_kuk' => 'Sistem penamaan file yang berdasarkan standar konvensi dan protocol'],
            ['id_kuk' => 13, 'id_elemen' => 5, 'deskripsi_kuk' => 'Sumber & review penyimpanan dan sistem backup ditetapkan'],
            ['id_kuk' => 14, 'id_elemen' => 6, 'deskripsi_kuk' => 'Pencarian dokumen dan asset media diatur'],
            ['id_kuk' => 15, 'id_elemen' => 6, 'deskripsi_kuk' => 'Konvensi untuk mencatat kemajuan dan lokasi asset media ditetapkan'],
            ['id_kuk' => 16, 'id_elemen' => 6, 'deskripsi_kuk' => 'Strategi pencarian dan pencatatan asset media dikembangkan'],
            ['id_kuk' => 17, 'id_elemen' => 6, 'deskripsi_kuk' => 'Sistem pengelolaan asset media disosialisaikan ke anggota tim saat sistem diterapkan'],
            ['id_kuk' => 18, 'id_elemen' => 7, 'deskripsi_kuk' => 'Sumber asset media sesuai prosedur didokumentasikan'],
            ['id_kuk' => 19, 'id_elemen' => 7, 'deskripsi_kuk' => 'Rincian dari berbagai output didokumentasikan sesuai informasi teknis, hak cipta dan perizinan'],
            ['id_kuk' => 20, 'id_elemen' => 7, 'deskripsi_kuk' => 'Persyaratan pengarsipan ditentukan'],
            ['id_kuk' => 21, 'id_elemen' => 8, 'deskripsi_kuk' => 'Asset media and informasi dicatat sesuai dengan sistem yang sudah mapan'],
            ['id_kuk' => 22, 'id_elemen' => 8, 'deskripsi_kuk' => 'Status produk, prototype dan asset media diindentifikasi'],
            ['id_kuk' => 23, 'id_elemen' => 8, 'deskripsi_kuk' => 'Menanggapi dan menyelesaikan permasalahan yang dihadapi saat sistem diimplementasikan'],
            ['id_kuk' => 24, 'id_elemen' => 9, 'deskripsi_kuk' => 'Jadwal untuk tenggang waktu dikonfirmasi dengan personil yang relevan'],
            ['id_kuk' => 25, 'id_elemen' => 9, 'deskripsi_kuk' => 'Berkas dan mengindeks dokumen formal diajukan sesuai dengan prosedur proyek atau perusahaan yang disepakati'],
            ['id_kuk' => 26, 'id_elemen' => 9, 'deskripsi_kuk' => 'Skrip file dan indeks disetujui sesuai dengan prosedur proyek atau perusahaan'],
            ['id_kuk' => 27, 'id_elemen' => 10, 'deskripsi_kuk' => 'Aset media dalam sistem repositori sistem yang mapan diarsipkan sesuai dengan praktik industri'],
            ['id_kuk' => 28, 'id_elemen' => 10, 'deskripsi_kuk' => 'Distribusi yang tepat oleh personil yang relevan ke dokumen formal dan aset media dipastikan yang dikembangkan dalam proyek'],
            ['id_kuk' => 29, 'id_elemen' => 10, 'deskripsi_kuk' => 'keefektifan sistem manajemen aset media dan perhatikan bidang-bidang dievaluasi untuk perbaikan di masa depan'],
            ['id_kuk' => 30, 'id_elemen' => 11, 'deskripsi_kuk' => 'Daftar teknologi yang saat ini dipakai disusun.'],
            ['id_kuk' => 31, 'id_elemen' => 11, 'deskripsi_kuk' => 'Daftar perangkat jaringan yang ada beserta kinerjanya disusun.'],
            ['id_kuk' => 32, 'id_elemen' => 12, 'deskripsi_kuk' => 'Perkembangan yang ada dari semua teknologi yang dipakai dirangkum.'],
            ['id_kuk' => 33, 'id_elemen' => 12, 'deskripsi_kuk' => 'Teknologi yang berpotensi meningkatkan kinerja jaringan ditentukan.'],
            ['id_kuk' => 34, 'id_elemen' => 13, 'deskripsi_kuk' => 'Ruang lingkup jaringan diidentifikasi sesuai dengan usulan.'],
            ['id_kuk' => 35, 'id_elemen' => 13, 'deskripsi_kuk' => 'Besarnya kapasitas jaringan dihitung berdasarkan kebutuhan bisnis.'],
            ['id_kuk' => 36, 'id_elemen' => 14, 'deskripsi_kuk' => 'Besaran bandwidth setiap segmen telah ditentukan.'],
            ['id_kuk' => 37, 'id_elemen' => 14, 'deskripsi_kuk' => 'Topologi lokasi penempatan perangkat jaringan telah dipilih dengan mempertimbangkan jarak dan jumlah pengguna.'],
            ['id_kuk' => 38, 'id_elemen' => 14, 'deskripsi_kuk' => 'Fitur-fitur fisik dipertimbangkan sebagai hasil dari desain jaringan.'],
            ['id_kuk' => 39, 'id_elemen' => 14, 'deskripsi_kuk' => 'Peta jaringan sesuai dengan keadaan gedung/lapangan dibuat.'],
            ['id_kuk' => 40, 'id_elemen' => 14, 'deskripsi_kuk' => 'Rancangan kebutuhan perkabelan disusun.'],
            ['id_kuk' => 41, 'id_elemen' => 14, 'deskripsi_kuk' => 'Biaya keseluruhan diperhitungkan.'],
            ['id_kuk' => 42, 'id_elemen' => 14, 'deskripsi_kuk' => 'Analisis proyeksi pengembangan jaringan dibuat.'],
            ['id_kuk' => 43, 'id_elemen' => 15, 'deskripsi_kuk' => 'Sistem operasi yang berjalan di jaringan diidentifikasi.'],
            ['id_kuk' => 44, 'id_elemen' => 15, 'deskripsi_kuk' => 'Informasi cara menginstal dan mengkonfigurasi jaringan pada sistem operasi yang dipakai dikumpulkan.'],
            ['id_kuk' => 45, 'id_elemen' => 16, 'deskripsi_kuk' => 'Jumlah node (host) jaringan ditentukan berdasarkan kebutuhan pengguna.'],
            ['id_kuk' => 46, 'id_elemen' => 16, 'deskripsi_kuk' => 'Kelas atau segmen alamat jaringan ditentukan berdasarkan besarnya jumlah node (host) jaringan.'],
            ['id_kuk' => 47, 'id_elemen' => 16, 'deskripsi_kuk' => 'Node atau perangkat jaringan diberi alamat jaringan.'],
            ['id_kuk' => 48, 'id_elemen' => 17, 'deskripsi_kuk' => 'Alamat masing-masing node atau perangkat jaringan dicatat.'],
            ['id_kuk' => 49, 'id_elemen' => 17, 'deskripsi_kuk' => 'Dokumentasi pengalamatan jaringan dibuat.'],
            ['id_kuk' => 50, 'id_elemen' => 18, 'deskripsi_kuk' => 'Topologi jaringan yang membutuhkan perangkat baru ditentukan.'],
            ['id_kuk' => 51, 'id_elemen' => 18, 'deskripsi_kuk' => 'Daftar perangkat jaringan dan rancangan kapasitasnya dibuat.'],
            ['id_kuk' => 52, 'id_elemen' => 18, 'deskripsi_kuk' => 'Perangkat komputer yang akan terhubung ke jaringan dipersiapkan.'],
            ['id_kuk' => 53, 'id_elemen' => 19, 'deskripsi_kuk' => 'Daftar perangkat jaringan yang dapat memenuhi kebutuhan dari berbagai vendor dibuat.'],
            ['id_kuk' => 54, 'id_elemen' => 19, 'deskripsi_kuk' => 'Rentang kapasitas yang mencakup perangkat jaringan yang ada di pasaran dituliskan.'],
            ['id_kuk' => 55, 'id_elemen' => 19, 'deskripsi_kuk' => 'Nilai kapasitas yang dapat dipenuhi oleh beberapa vendor ditentukan.'],
            ['id_kuk' => 56, 'id_elemen' => 20, 'deskripsi_kuk' => 'Dokumen spesifikasi perangkat jaringan dibuat.'],
            ['id_kuk' => 57, 'id_elemen' => 20, 'deskripsi_kuk' => 'Spesifikasi yang sesuai dengan pasar dan kebutuhan dikumpulkan.'],
            ['id_kuk' => 58, 'id_elemen' => 21, 'deskripsi_kuk' => 'Prosedur instalasi jaringan yang aman baik dari segi elektris maupun konstruksi disiapkan.'],
            ['id_kuk' => 59, 'id_elemen' => 21, 'deskripsi_kuk' => 'Diagram jalur perkabelan dibuat.'],
            ['id_kuk' => 60, 'id_elemen' => 21, 'deskripsi_kuk' => 'Jadwal dan urutan penyelesaian pekerjaan ditentukan.'],
            ['id_kuk' => 61, 'id_elemen' => 22, 'deskripsi_kuk' => 'Soket RJ-45 dipasang pada dinding di wiring closet.'],
            ['id_kuk' => 62, 'id_elemen' => 22, 'deskripsi_kuk' => 'Perangkat dalam wiring closet dipasang.'],
            ['id_kuk' => 63, 'id_elemen' => 22, 'deskripsi_kuk' => 'Terminal utama (main distribution frame) atau terminal cabang (intermediate distribution frame) dipasang jika diperlukan.'],
            ['id_kuk' => 64, 'id_elemen' => 22, 'deskripsi_kuk' => 'Jalur kabel disiapkan.'],
            ['id_kuk' => 65, 'id_elemen' => 22, 'deskripsi_kuk' => 'Pelabelan kabel dilakukan dengan benar.'],
            ['id_kuk' => 66, 'id_elemen' => 23, 'deskripsi_kuk' => 'Topologi fisik jaringan digambarkan.'],
            ['id_kuk' => 67, 'id_elemen' => 23, 'deskripsi_kuk' => 'Topologi logis jaringan digambarkan.'],
            ['id_kuk' => 68, 'id_elemen' => 23, 'deskripsi_kuk' => 'Outlet and jalur kabel dicatat.'],
            ['id_kuk' => 69, 'id_elemen' => 23, 'deskripsi_kuk' => 'Perangkat, MAC address dan IP address didokumentasikan.'],
            ['id_kuk' => 70, 'id_elemen' => 24, 'deskripsi_kuk' => 'Konsep data dan struktur data diidentifikasi sesuai dengan konteks permasalahan.'],
            ['id_kuk' => 71, 'id_elemen' => 24, 'deskripsi_kuk' => 'Alternatif struktur data dibandingkan kelebihan dan kekurangannya untuk konteks permasalahan yang diselesaikan.'],
            ['id_kuk' => 72, 'id_elemen' => 25, 'deskripsi_kuk' => 'Struktur data diimplementasikan sesuai dengan bahasa pemrograman yang akan dipergunakan.'],
            ['id_kuk' => 73, 'id_elemen' => 25, 'deskripsi_kuk' => 'Akses terhadap data dinyatakan dalam algoritma yang efisiensi sesuai bahasa pemrograman yang akan dipakai.'],
            ['id_kuk' => 74, 'id_elemen' => 26, 'deskripsi_kuk' => 'Metode pengembangan aplikasi (software development) didefinisikan.'],
            ['id_kuk' => 75, 'id_elemen' => 26, 'deskripsi_kuk' => 'Metode pengembangan aplikasi (software development) dipilih sesuai kebutuhan.'],
            ['id_kuk' => 76, 'id_elemen' => 27, 'deskripsi_kuk' => 'Diagram program dengan metodologi pengembangan sistem didefinisikan.'],
            ['id_kuk' => 77, 'id_elemen' => 27, 'deskripsi_kuk' => 'Metode pemodelan, diagram objek dan diagram komponen digunakan pada implementasi program sesuai dengan spesifikasi.'],
            ['id_kuk' => 78, 'id_elemen' => 28, 'deskripsi_kuk' => 'Hasil pemodelan yang mendukung kemampuan metodologi dipilih sesuai spesifikasi.'],
            ['id_kuk' => 79, 'id_elemen' => 28, 'deskripsi_kuk' => 'Hasil pemrograman (Integrated Development Environment-IDE) yang mendukung kemampuan metodologi bahasa pemrograman dipilih sesuai spesifikasi.'],
            ['id_kuk' => 80, 'id_elemen' => 29, 'deskripsi_kuk' => 'Cara and tools untuk mengeksekusi source code diidentifikasi.'],
            ['id_kuk' => 81, 'id_elemen' => 29, 'deskripsi_kuk' => 'Parameter untuk mengeksekusi source code diidentifikasi.'],
            ['id_kuk' => 82, 'id_elemen' => 29, 'deskripsi_kuk' => 'Peletakan source code sehingga bisa dieksekusi dengan benar diidentifikasi.'],
            ['id_kuk' => 83, 'id_elemen' => 30, 'deskripsi_kuk' => 'Source code dieksekusi sesuai dengan mekanisme eksekusi source code from tools pemrograman yang digunakan.'],
            ['id_kuk' => 84, 'id_elemen' => 30, 'deskripsi_kuk' => 'Perbedaan antara running, debugging, atau membuat executable file diidentifikasi.'],
            ['id_kuk' => 85, 'id_elemen' => 31, 'deskripsi_kuk' => 'Source code berhasil dieksekusi sesuai skenario yang direncanakan.'],
            ['id_kuk' => 86, 'id_elemen' => 31, 'deskripsi_kuk' => 'Jika eksekusi source code gagal/tidak berhasil, sumber permasalahan diidentifikasi.'],
            ['id_kuk' => 87, 'id_elemen' => 32, 'deskripsi_kuk' => 'Kode sumber dituliskan mengikuti coding-guidelines dan best practices.'],
            ['id_kuk' => 88, 'id_elemen' => 32, 'deskripsi_kuk' => 'Struktur program yang sesuai dengan konsep paradigmanya dibuat.'],
            ['id_kuk' => 89, 'id_elemen' => 32, 'deskripsi_kuk' => 'Galat/error ditangani.'],
            ['id_kuk' => 90, 'id_elemen' => 33, 'deskripsi_kuk' => 'Efisiensi penggunaan resources oleh kode dihitung.'],
            ['id_kuk' => 91, 'id_elemen' => 33, 'deskripsi_kuk' => 'Kemudahan interaksi selalu diimplementasikan sesuai standar yang berlaku.'],
            ['id_kuk' => 92, 'id_elemen' => 34, 'deskripsi_kuk' => 'Tipe data yang sesuai standar ditentukan.'],
            ['id_kuk' => 93, 'id_elemen' => 34, 'deskripsi_kuk' => 'Syntax program yang dikuasai digunakan sesuai standar.'],
            ['id_kuk' => 94, 'id_elemen' => 34, 'deskripsi_kuk' => 'Struktur kontrol program yang dikuasai digunakan sesuai standar.'],
            ['id_kuk' => 95, 'id_elemen' => 35, 'deskripsi_kuk' => 'Program baca tulis untuk memasukkan data dari keyboard dan menampilkan ke layar monitor termasuk variasinya sesuai standar masukan/keluaran telah dibuat.'],
            ['id_kuk' => 96, 'id_elemen' => 35, 'deskripsi_kuk' => 'Struktur kontrol percabangan dan pengulangan dalam membuat program telah digunakan.'],
            ['id_kuk' => 97, 'id_elemen' => 36, 'deskripsi_kuk' => 'Program dengan menggunakan prosedur dibuat sesuai aturan penulisan program.'],
            ['id_kuk' => 98, 'id_elemen' => 36, 'deskripsi_kuk' => 'Program dengan menggunakan fungsi dibuat sesuai aturan penulisan program.'],
            ['id_kuk' => 99, 'id_elemen' => 36, 'deskripsi_kuk' => 'Program dengan menggunakan prosedur and fungsi secara bersamaan dibuat sesuai aturan penulisan program.'],
            ['id_kuk' => 100, 'id_elemen' => 36, 'deskripsi_kuk' => 'Keterangan untuk setiap prosedur and fungsi telah diberikan.'],
            ['id_kuk' => 101, 'id_elemen' => 37, 'deskripsi_kuk' => 'Dimensi array telah ditentukan.'],
            ['id_kuk' => 102, 'id_elemen' => 37, 'deskripsi_kuk' => 'Tipe data array telah ditentukan.'],
            ['id_kuk' => 103, 'id_elemen' => 37, 'deskripsi_kuk' => 'Panjang array telah ditentukan.'],
            ['id_kuk' => 104, 'id_elemen' => 37, 'deskripsi_kuk' => 'Pengurutan array telah digunakan.'],
            ['id_kuk' => 105, 'id_elemen' => 38, 'deskripsi_kuk' => 'Program untuk menulis data dalam media penyimpan telah dibuat.'],
            ['id_kuk' => 106, 'id_elemen' => 38, 'deskripsi_kuk' => 'Program untuk membaca data dari media penyimpan telah dibuat.'],
            ['id_kuk' => 107, 'id_elemen' => 39, 'deskripsi_kuk' => 'Kesalahan program telah dikoreksi.'],
            ['id_kuk' => 108, 'id_elemen' => 39, 'deskripsi_kuk' => 'Kesalahan syntax dalam program telah dibebaskan.'],
            ['id_kuk' => 109, 'id_elemen' => 40, 'deskripsi_kuk' => 'Modul program diidentifikasi'],
            ['id_kuk' => 110, 'id_elemen' => 40, 'deskripsi_kuk' => 'Parameter yang dipergunakan diidentifikasi'],
            ['id_kuk' => 111, 'id_elemen' => 40, 'deskripsi_kuk' => 'Algoritma dijelaskan cara kerjanya'],
            ['id_kuk' => 112, 'id_elemen' => 40, 'deskripsi_kuk' => 'Komentar setiap baris kode termasuk data, eksepsi, fungsi, prosedur dan class (bila ada) diberikan'],
            ['id_kuk' => 113, 'id_elemen' => 41, 'deskripsi_kuk' => 'Dokumentasi modul dibuat sesuai dengan identitas untuk memudahkan pelacakan'],
            ['id_kuk' => 114, 'id_elemen' => 41, 'deskripsi_kuk' => 'Identifikasi dokumentasi diterapkan'],
            ['id_kuk' => 115, 'id_elemen' => 41, 'deskripsi_kuk' => 'Kegunaan modul dijelaskan'],
            ['id_kuk' => 116, 'id_elemen' => 41, 'deskripsi_kuk' => 'Dokumen direvisi sesuai perubahan kode program'],
            ['id_kuk' => 117, 'id_elemen' => 42, 'deskripsi_kuk' => 'Dokumentasi fungsi, prosedur atau metod dibuat'],
            ['id_kuk' => 118, 'id_elemen' => 42, 'deskripsi_kuk' => 'Kemungkinan eksepsi dijelaskan'],
            ['id_kuk' => 119, 'id_elemen' => 42, 'deskripsi_kuk' => 'Dokumen direvisi sesuai perubahan kode program'],
            ['id_kuk' => 120, 'id_elemen' => 43, 'deskripsi_kuk' => 'Tools untuk generate dokumentasi diidentifikasi'],
            ['id_kuk' => 121, 'id_elemen' => 43, 'deskripsi_kuk' => 'Generate dokumentasi dilakukan'],
            ['id_kuk' => 122, 'id_elemen' => 44, 'deskripsi_kuk' => 'Kode program sesuai spesifikasi disiapkan.'],
            ['id_kuk' => 123, 'id_elemen' => 44, 'deskripsi_kuk' => 'Debugging tools untuk melihat proses suatu modul dipersiapkan.'],
            ['id_kuk' => 124, 'id_elemen' => 45, 'deskripsi_kuk' => 'Kode program dikompilasi sesuai bahasa pemrograman yang digunakan.'],
            ['id_kuk' => 125, 'id_elemen' => 45, 'deskripsi_kuk' => 'Kriteria lulus build dianalisis.'],
            ['id_kuk' => 126, 'id_elemen' => 45, 'deskripsi_kuk' => 'Kriteria eksekusi aplikasi dianalisis.'],
            ['id_kuk' => 127, 'id_elemen' => 45, 'deskripsi_kuk' => 'Kode kesalahan dicatat.'],
            ['id_kuk' => 128, 'id_elemen' => 46, 'deskripsi_kuk' => 'Perbaikan terhadap kesalahan kompilasi maupun build dirumuskan.'],
            ['id_kuk' => 129, 'id_elemen' => 46, 'deskripsi_kuk' => 'Perbaikan dilakukan'],
            ['id_kuk' => 130, 'id_elemen' => 47, 'deskripsi_kuk' => 'Prosedur uji coba aplikasi diidentifikasikan sesuai dengan software development life cycle.'],
            ['id_kuk' => 131, 'id_elemen' => 47, 'deskripsi_kuk' => 'Tools uji coba ditentukan.'],
            ['id_kuk' => 132, 'id_elemen' => 47, 'deskripsi_kuk' => 'Standar and kondisi uji coba diidentifikasi.'],
            ['id_kuk' => 133, 'id_elemen' => 48, 'deskripsi_kuk' => 'Kebutuhan untuk uji coba ditentukan.'],
            ['id_kuk' => 134, 'id_elemen' => 48, 'deskripsi_kuk' => 'Uji coba dengan variasi kondisi dapat dilaksanakan.'],
            ['id_kuk' => 135, 'id_elemen' => 48, 'deskripsi_kuk' => 'Skenario uji coba dibuat.'],
            ['id_kuk' => 136, 'id_elemen' => 49, 'deskripsi_kuk' => 'Data uji unit tes diidentifikasi.'],
            ['id_kuk' => 137, 'id_elemen' => 49, 'deskripsi_kuk' => 'Data uji unit tes dibangkitkan.'],
            ['id_kuk' => 138, 'id_elemen' => 50, 'deskripsi_kuk' => 'Skenario uji coba didesain.'],
            ['id_kuk' => 139, 'id_elemen' => 50, 'deskripsi_kuk' => 'Prosedur uji coba dalam algoritma didesain.'],
            ['id_kuk' => 140, 'id_elemen' => 50, 'deskripsi_kuk' => 'Uji coba dilaksanakan.'],
            ['id_kuk' => 141, 'id_elemen' => 51, 'deskripsi_kuk' => 'Hasil uji coba dicatat.'],
            ['id_kuk' => 142, 'id_elemen' => 51, 'deskripsi_kuk' => 'Hasil uji coba dianalisis.'],
            ['id_kuk' => 143, 'id_elemen' => 51, 'deskripsi_kuk' => 'Prosedur uji coba dilaporkan.'],
            ['id_kuk' => 144, 'id_elemen' => 51, 'deskripsi_kuk' => 'Kesalahan/error diselesaikan.'],
            ['id_kuk' => 145, 'id_elemen' => 52, 'deskripsi_kuk' => 'Surat/dokumen yang diterima diidentifikasi sesuai prosedur organisasi.'],
            ['id_kuk' => 146, 'id_elemen' => 52, 'deskripsi_kuk' => 'Surat/dokumen disortir sesuai dengan tujuannya'],
            ['id_kuk' => 147, 'id_elemen' => 52, 'deskripsi_kuk' => 'Berita dalam surat/dokumen termasuk surat elektronik diperiksa keakuratannya.'],
            ['id_kuk' => 148, 'id_elemen' => 52, 'deskripsi_kuk' => 'Lampiran surat /dokumen termasuk surat elektronik diidentifikasi sesuai prosedur organisasi.'],
            ['id_kuk' => 149, 'id_elemen' => 52, 'deskripsi_kuk' => 'Surat/dokumen dicatat sesuai dengan sistem yang ada pada organisasi.'],
            ['id_kuk' => 150, 'id_elemen' => 53, 'deskripsi_kuk' => 'Daftar distribusi disiapkan sesuai prosedur organisasi.'],
            ['id_kuk' => 151, 'id_elemen' => 53, 'deskripsi_kuk' => 'Pendistribusian surat/dokumen dilakukan dengan batas waktu.'],
            ['id_kuk' => 152, 'id_elemen' => 53, 'deskripsi_kuk' => 'Salinan surat/dokumen dibuat sesuai prosedur organisasi.'],
            ['id_kuk' => 153, 'id_elemen' => 53, 'deskripsi_kuk' => 'Pilihan cara pengiriman ditetapkan dengan benar dan yang terbaik sesuai kebutuhan.'],
            ['id_kuk' => 154, 'id_elemen' => 53, 'deskripsi_kuk' => 'Tanda terima surat/dokumen didokumentasikan sesuai prosedur organisasi.'],
            ['id_kuk' => 155, 'id_elemen' => 54, 'deskripsi_kuk' => 'Teknologi dan perangkat lunak dipilih untuk menghasilkan dokumen yang dibutuhkan.'],
            ['id_kuk' => 156, 'id_elemen' => 54, 'deskripsi_kuk' => 'Persyaratan Organisasi diidentifikasi untuk menciptakan informasi sesuai rencana.'],
            ['id_kuk' => 157, 'id_elemen' => 55, 'deskripsi_kuk' => 'Pointers untuk isi dokumen dibuat sesuai kebutuhan.'],
            ['id_kuk' => 158, 'id_elemen' => 55, 'deskripsi_kuk' => 'Format ditentukan sesuai dengan ketentuan organisasi.'],
            ['id_kuk' => 159, 'id_elemen' => 55, 'deskripsi_kuk' => 'Peralatan untuk menciptakan dokumen ditentukan sesuai kebutuhan.'],
            ['id_kuk' => 160, 'id_elemen' => 56, 'deskripsi_kuk' => 'Waktu untuk memproduksi dokumen ditentukan sesuai dengan persyaratan organisasi.'],
            ['id_kuk' => 161, 'id_elemen' => 56, 'deskripsi_kuk' => 'Dokumen dibuat sesuai format.'],
            ['id_kuk' => 162, 'id_elemen' => 56, 'deskripsi_kuk' => 'Dokumen yang diproduksi diperiksa redaksionalnya sesuai persyaratan organisasi.'],
            ['id_kuk' => 163, 'id_elemen' => 57, 'deskripsi_kuk' => 'Informasi jadwal kegiatan pimpinan diperoleh melalui departemen internal atau pihak luar yang terkait.'],
            ['id_kuk' => 164, 'id_elemen' => 57, 'deskripsi_kuk' => 'Informasi pada dokumen pendukung diidentifikasi sesuai dengan kegiatan.'],
            ['id_kuk' => 165, 'id_elemen' => 57, 'deskripsi_kuk' => 'Jadwal hari libur nasional dan hari cuti pimpinan di identifikasi.'],
            ['id_kuk' => 166, 'id_elemen' => 58, 'deskripsi_kuk' => 'Kegiatan diseleksi sesuai kebutuhan organisasi dan arahan pimpinan.'],
            ['id_kuk' => 167, 'id_elemen' => 58, 'deskripsi_kuk' => 'Kehadiran pimpinan pada kegiatan dikonfirmasikan.'],
            ['id_kuk' => 168, 'id_elemen' => 58, 'deskripsi_kuk' => 'Jadwal kegiatan/perjalanan pimpinan disusun.'],
            ['id_kuk' => 169, 'id_elemen' => 59, 'deskripsi_kuk' => 'Metode pencatatan kegiatan yang digunakan diidentifikasi.'],
            ['id_kuk' => 170, 'id_elemen' => 59, 'deskripsi_kuk' => 'Jadwal kegiatan dibuat sesuai format pada organisasi.'],
            ['id_kuk' => 171, 'id_elemen' => 59, 'deskripsi_kuk' => 'Jadwal kegiatan pimpinan diperbaharui secara berkala.'],
            ['id_kuk' => 172, 'id_elemen' => 60, 'deskripsi_kuk' => 'Daftar nama peserta rapat dipastikan sesuai tujuan rapat/pertemuan.'],
            ['id_kuk' => 173, 'id_elemen' => 60, 'deskripsi_kuk' => 'Tujuan dan rangkaian acara pertemuan di susun sesuai arahan pimpinan dan protokoler yang berlaku di organisasi.'],
            ['id_kuk' => 174, 'id_elemen' => 60, 'deskripsi_kuk' => 'Waktu, tempat dan ketentuan pertemuan ditetapkan.'],
            ['id_kuk' => 175, 'id_elemen' => 60, 'deskripsi_kuk' => 'Undangan rapat dibuat sesuai kegiatan.'],
            ['id_kuk' => 176, 'id_elemen' => 60, 'deskripsi_kuk' => 'Undangan dikirim melalui media yang dipilih.'],
            ['id_kuk' => 177, 'id_elemen' => 61, 'deskripsi_kuk' => 'Ruangan pertemuan dan konsumsi dipesan sesuai kebutuhan.'],
            ['id_kuk' => 178, 'id_elemen' => 61, 'deskripsi_kuk' => 'Layout ruangan ditentukan sesuai kebutuhan.'],
            ['id_kuk' => 179, 'id_elemen' => 61, 'deskripsi_kuk' => 'Peralatan dan perlengkapan pendukung diidentifikasi sesuai kebutuhan.'],
            ['id_kuk' => 180, 'id_elemen' => 61, 'deskripsi_kuk' => 'Tenaga profesional disiapkan sesuai kebutuhan.'],
            ['id_kuk' => 181, 'id_elemen' => 62, 'deskripsi_kuk' => 'Rincian anggaran dibuat untuk mendapatkan persetujuan pimpinan.'],
            ['id_kuk' => 182, 'id_elemen' => 62, 'deskripsi_kuk' => 'Rincian anggaran ditindaklanjuti kepada bagian terkait.'],
            ['id_kuk' => 183, 'id_elemen' => 62, 'deskripsi_kuk' => 'Anggaran dikelola sesuai rincian yang telah ditetapkan.'],
            ['id_kuk' => 184, 'id_elemen' => 62, 'deskripsi_kuk' => 'Bukti kwitansi/tanda terima dicatat sebagai lampiran laporan penggunaan biaya.'],
            ['id_kuk' => 185, 'id_elemen' => 63, 'deskripsi_kuk' => 'Kehadiran peserta dikonfirmasi.'],
            ['id_kuk' => 186, 'id_elemen' => 63, 'deskripsi_kuk' => 'Pengaturan ruangan, konsumsi, diperiksa sesuai dengan pesanan.'],
            ['id_kuk' => 187, 'id_elemen' => 63, 'deskripsi_kuk' => 'Peralatan dan perlengkapan disiapkan sesuai kebutuhan.'],
            ['id_kuk' => 188, 'id_elemen' => 63, 'deskripsi_kuk' => 'Pertemuan dilaksanakan sesuai rangkaian agenda yang telah ditetapkan.'],
            ['id_kuk' => 189, 'id_elemen' => 64, 'deskripsi_kuk' => 'Jumlah peserta yang hadir dilaporkan.'],
            ['id_kuk' => 190, 'id_elemen' => 64, 'deskripsi_kuk' => 'Laporan penggunaan biaya dibuat sesuai dengan aturan organisasi.'],
            ['id_kuk' => 191, 'id_elemen' => 65, 'deskripsi_kuk' => 'Panggilan telepon dijawab sesuai dengan SOP.'],
            ['id_kuk' => 192, 'id_elemen' => 65, 'deskripsi_kuk' => 'Bantuan ditawarkan kepada penelepon sesuai SOP.'],
            ['id_kuk' => 193, 'id_elemen' => 65, 'deskripsi_kuk' => 'Inti pembicaraan diulangi untuk menghindari salah pengertian.'],
            ['id_kuk' => 194, 'id_elemen' => 65, 'deskripsi_kuk' => 'Pertanyaan penelpon dijawab atau meneruskannya kepada orang yang tepat.'],
            ['id_kuk' => 195, 'id_elemen' => 66, 'deskripsi_kuk' => 'Nomor telepon didapatkan dari sumber yang benar.'],
            ['id_kuk' => 196, 'id_elemen' => 66, 'deskripsi_kuk' => 'Sebelum menelpon tujuan dipastikan dengan tepat.'],
            ['id_kuk' => 197, 'id_elemen' => 66, 'deskripsi_kuk' => 'Nama organisasi dan alasan menelepon disampaikan sesuai SOP.'],
            ['id_kuk' => 198, 'id_elemen' => 66, 'deskripsi_kuk' => 'Etika bertelepon sesuai SOP diterapkan saat berbicara melalui telepon.'],
            ['id_kuk' => 199, 'id_elemen' => 67, 'deskripsi_kuk' => 'Pesan yang diterima dicatat secara akurat untuk disampaikan kepada departemen/orang yang dimaksud.'],
            ['id_kuk' => 200, 'id_elemen' => 67, 'deskripsi_kuk' => 'Pesan disampaikan segera kepada orang yang berhak menerimanya.'],
            ['id_kuk' => 201, 'id_elemen' => 67, 'deskripsi_kuk' => 'Panggilan telepon yang mengancam dan mencurigakan di laporkan dengan cepat kepada yang berwenang sesuai dengan SOP.'],
            ['id_kuk' => 202, 'id_elemen' => 68, 'deskripsi_kuk' => 'Karakteristik komunikan diidentifikasi.'],
            ['id_kuk' => 203, 'id_elemen' => 68, 'deskripsi_kuk' => 'Metode komunikasi ditentukan.'],
            ['id_kuk' => 204, 'id_elemen' => 69, 'deskripsi_kuk' => 'Lingkungan pelayanan yang efektif diciptakan.'],
            ['id_kuk' => 205, 'id_elemen' => 69, 'deskripsi_kuk' => 'Permintaan informasi komunikan diterima.'],
            ['id_kuk' => 206, 'id_elemen' => 69, 'deskripsi_kuk' => 'Kebutuhan komunikan dieksplorasi.'],
            ['id_kuk' => 207, 'id_elemen' => 70, 'deskripsi_kuk' => 'Pesan atau informasi yang diterima dicatat untuk diolah.'],
            ['id_kuk' => 208, 'id_elemen' => 70, 'deskripsi_kuk' => 'Jawaban diberikan sesuai kebutuhan.'],
            ['id_kuk' => 209, 'id_elemen' => 70, 'deskripsi_kuk' => 'Tindakan lebih lanjut dilakukan.'],
            ['id_kuk' => 210, 'id_elemen' => 70, 'deskripsi_kuk' => 'Pelaksanaan komunikasi dievaluasi.'],
            ['id_kuk' => 211, 'id_elemen' => 71, 'deskripsi_kuk' => 'Komunikasi timbal balik dengan komunikan dilakukan.'],
            ['id_kuk' => 212, 'id_elemen' => 71, 'deskripsi_kuk' => 'Informasi faktual dan terkini diberikan sesuai SOP organisasi and kebutuhan pelanggan.'],
            ['id_kuk' => 213, 'id_elemen' => 71, 'deskripsi_kuk' => 'Permintaan atau pertanyaan-pertanyaan yang bersifat sederhana dijawab.'],
            ['id_kuk' => 214, 'id_elemen' => 71, 'deskripsi_kuk' => 'Bantuan diberikan dalam lingkup tanggung jawabnya.'],
            ['id_kuk' => 215, 'id_elemen' => 71, 'deskripsi_kuk' => 'Saran/usul diberikan untuk hal-hal tertentu sesuai dengan SOP.'],
            ['id_kuk' => 216, 'id_elemen' => 71, 'deskripsi_kuk' => 'Kebutuhan bantuan yang diperlukan dari orang lain diidentifikasi.'],
            ['id_kuk' => 217, 'id_elemen' => 71, 'deskripsi_kuk' => 'Penjelasan yang mudah dilakukan dengan perlahan-lahan dan berurutan.'],
            ['id_kuk' => 218, 'id_elemen' => 71, 'deskripsi_kuk' => 'Informasi tambahan diberikan sesuai dengan kebutuhan pelanggan dan kolega.'],
            ['id_kuk' => 219, 'id_elemen' => 72, 'deskripsi_kuk' => 'Kalimat resmi dan tidak resmi diidentifikasi untuk digunakan.'],
            ['id_kuk' => 220, 'id_elemen' => 72, 'deskripsi_kuk' => 'Sapaan diberikan dengan santun sesuai etika berkomunikasi.'],
            ['id_kuk' => 221, 'id_elemen' => 72, 'deskripsi_kuk' => 'Salam perpisahan diberikan sesuai SOP organisasi.'],
            ['id_kuk' => 222, 'id_elemen' => 72, 'deskripsi_kuk' => 'Permintaan maaf diajukan sesuai SOP organisasi.'],
            ['id_kuk' => 223, 'id_elemen' => 73, 'deskripsi_kuk' => 'Salam diberikan termasuk menyebutkan nama organisasi sesuai SOP organisasi.'],
            ['id_kuk' => 224, 'id_elemen' => 73, 'deskripsi_kuk' => 'Bantuan ditawarkan kepada penelepon.'],
            ['id_kuk' => 225, 'id_elemen' => 73, 'deskripsi_kuk' => 'Penelepon diminta untuk menunggu ketika sedang mencari orang yang dikehendaki penelpon.'],
            ['id_kuk' => 226, 'id_elemen' => 73, 'deskripsi_kuk' => 'Permintaan maaf disampaikan kepada penelepon ketika orang yang dikehendaki tidak berada di tempat ataupun tidak mampu memenuhi permintaan penelepon.'],
            ['id_kuk' => 227, 'id_elemen' => 73, 'deskripsi_kuk' => 'Data dan pesan penelepon dicatat secara lengkap'],
            ['id_kuk' => 228, 'id_elemen' => 74, 'deskripsi_kuk' => 'Tanda-tanda baca bahasa Inggris ditafsirkan maknanya.'],
            ['id_kuk' => 229, 'id_elemen' => 74, 'deskripsi_kuk' => 'Tanda-tanda umum yang biasa digunakan diketahui pengertiannya.'],
            ['id_kuk' => 230, 'id_elemen' => 75, 'deskripsi_kuk' => 'Maksud dan isi dokumen diidentifikasi'],
            ['id_kuk' => 231, 'id_elemen' => 75, 'deskripsi_kuk' => 'Maksud dari dokumen ditanggapi bila perlu.'],
            ['id_kuk' => 232, 'id_elemen' => 75, 'deskripsi_kuk' => 'Bantuan dicari bila perlu.'],
            ['id_kuk' => 233, 'id_elemen' => 76, 'deskripsi_kuk' => 'Tujuan dan inti teks diidentifikasi.'],
            ['id_kuk' => 234, 'id_elemen' => 76, 'deskripsi_kuk' => 'Tanggapan diberikan terhadap maksud dari teks yang dibutuhkan'],
            ['id_kuk' => 235, 'id_elemen' => 76, 'deskripsi_kuk' => 'Bantuan dicari bila perlu.'],
            ['id_kuk' => 236, 'id_elemen' => 77, 'deskripsi_kuk' => 'Tujuan penulisan diidentifikasi.'],
            ['id_kuk' => 237, 'id_elemen' => 77, 'deskripsi_kuk' => 'Jenis dokumen yang tepat sebagai pendukung dipilih untuk dipersiapkan.'],
            ['id_kuk' => 238, 'id_elemen' => 77, 'deskripsi_kuk' => 'Bahasa yang digunakan sesuai dengan kaidah tata bahasa untuk memenuhi kebutuhan konteks.'],
            ['id_kuk' => 239, 'id_elemen' => 77, 'deskripsi_kuk' => 'Kaidah tata bahasa yang umum dalam bisnis diperhatikan dan diikuti.'],
            ['id_kuk' => 240, 'id_elemen' => 77, 'deskripsi_kuk' => 'Informasi disampaikan secara objektif.'],
            ['id_kuk' => 241, 'id_elemen' => 78, 'deskripsi_kuk' => 'Kalimat sederhana digunakan dalam menyampaikan suatu pengertian.'],
            ['id_kuk' => 242, 'id_elemen' => 78, 'deskripsi_kuk' => 'Instruksi dan/atau petunjuk dijabarkan dengan benar.'],
            ['id_kuk' => 243, 'id_elemen' => 78, 'deskripsi_kuk' => 'Kaidah tata bahasa yang umum dalam bisnis diikuti.'],
            ['id_kuk' => 244, 'id_elemen' => 78, 'deskripsi_kuk' => 'Bahasa yang tepat untuk memenuhi kebutuhan konteks digunakan sesuai kebutuhan.'],
            ['id_kuk' => 245, 'id_elemen' => 78, 'deskripsi_kuk' => 'Kalimat diruntut sesuai dengan SOP.'],
            ['id_kuk' => 246, 'id_elemen' => 78, 'deskripsi_kuk' => 'Bahasa resmi dan tidak resmi digunakan dengan tepat.'],
            ['id_kuk' => 247, 'id_elemen' => 79, 'deskripsi_kuk' => 'Konsep pelayanan diidentifikasi sesuai kebutuhan.'],
            ['id_kuk' => 248, 'id_elemen' => 79, 'deskripsi_kuk' => 'Prinsip-prinsip pelayanan prima diterapkan sesuai dengan SOP organisasi.'],
            ['id_kuk' => 249, 'id_elemen' => 80, 'deskripsi_kuk' => 'Unsur-unsur kualitas pelayanan prima diterapkan.'],
            ['id_kuk' => 250, 'id_elemen' => 80, 'deskripsi_kuk' => 'Kualitas pelayanan ditingkatkan secara efektif dan efisien.'],
            ['id_kuk' => 251, 'id_elemen' => 81, 'deskripsi_kuk' => 'Kebutuhan Pelayanan diidentifikasi sesuai SOP.'],
            ['id_kuk' => 252, 'id_elemen' => 81, 'deskripsi_kuk' => 'Keluhan pelanggan ditangani sesuai dengan prosedur organisasi.'],
            ['id_kuk' => 253, 'id_elemen' => 81, 'deskripsi_kuk' => 'Hubungan dengan pelanggan dibangun untuk memberikan pelayanan yang maksimal sesuai dengan kebutuhan pelanggan.'],
            ['id_kuk' => 254, 'id_elemen' => 81, 'deskripsi_kuk' => 'Bahasa dan sikap yang baik digunakan sesuai SOP.'],
            ['id_kuk' => 255, 'id_elemen' => 82, 'deskripsi_kuk' => 'Peralatan komputer disiapkan sesuai dengan SOP.'],
            ['id_kuk' => 256, 'id_elemen' => 82, 'deskripsi_kuk' => 'Piranti lunak dipilih melalui menu sesuai dengan kebutuhan.'],
            ['id_kuk' => 257, 'id_elemen' => 82, 'deskripsi_kuk' => 'Media penyimpanan disiapkan sesuai kebutuhan.'],
            ['id_kuk' => 258, 'id_elemen' => 83, 'deskripsi_kuk' => 'Keyboard/mouse dioperasikan sesuai SOP.'],
            ['id_kuk' => 259, 'id_elemen' => 83, 'deskripsi_kuk' => 'Konsep dokumen diedit sesuai dengan format standar tempat kerja.'],
            ['id_kuk' => 260, 'id_elemen' => 83, 'deskripsi_kuk' => 'Dokumen pendukung dibuat bila diperlukan.'],
            ['id_kuk' => 261, 'id_elemen' => 84, 'deskripsi_kuk' => 'Memastikan nama file/folder penyimpanan dokumen yang dibuat, disimpan sesuai SOP.'],
            ['id_kuk' => 262, 'id_elemen' => 84, 'deskripsi_kuk' => 'Salinan file/dokumen dibuat bila diperlukan.'],
            ['id_kuk' => 263, 'id_elemen' => 85, 'deskripsi_kuk' => 'File/dokumen/naskah yang akan dicetak diidentifikasi sesuai SOP.'],
            ['id_kuk' => 264, 'id_elemen' => 85, 'deskripsi_kuk' => 'Fitur-fitur pencetakan diidentifikasi sesuai kebutuhan.'],
            ['id_kuk' => 265, 'id_elemen' => 85, 'deskripsi_kuk' => 'File/dokumen/naskah dicetak dengan menggunakan parameter dan urutan pencetakan sesuai prosedur pencetakan.'],
            ['id_kuk' => 266, 'id_elemen' => 86, 'deskripsi_kuk' => 'Jenis komunikasi yang akan dilakukan dipastikan.'],
            ['id_kuk' => 267, 'id_elemen' => 86, 'deskripsi_kuk' => 'Peralatan komunikasi diidentifikasi, sesuai dengan jenis komunikasi yang akan dilakukan.'],
            ['id_kuk' => 268, 'id_elemen' => 86, 'deskripsi_kuk' => 'Peralatan komunikasi yang tepat dipilih sesuai kebutuhan.'],
            ['id_kuk' => 269, 'id_elemen' => 87, 'deskripsi_kuk' => 'Peralatan komunikasi digunakan sesuai SOP.'],
            ['id_kuk' => 270, 'id_elemen' => 87, 'deskripsi_kuk' => 'Peralatan yang tidak berfungsi dilaporkan kepada pihak terkait.'],
            ['id_kuk' => 271, 'id_elemen' => 87, 'deskripsi_kuk' => 'Tindakan alternatif segera dilakukan bila alat komunikasi tidak berfungsi.'],
            ['id_kuk' => 272, 'id_elemen' => 87, 'deskripsi_kuk' => 'Peralatan komunikasi digunakan sesuai dengan panduan penggunaan.'],
            ['id_kuk' => 273, 'id_elemen' => 88, 'deskripsi_kuk' => 'Pilihan aplikasi yang dibutuhkan di identifikasi.'],
            ['id_kuk' => 274, 'id_elemen' => 88, 'deskripsi_kuk' => 'Metode pencarian secara tepat, dipilih untuk penggunaan tipe informasi.'],
            ['id_kuk' => 275, 'id_elemen' => 89, 'deskripsi_kuk' => 'Aplikasi piranti lunak dipilih sesuai kebutuhan'],
            ['id_kuk' => 276, 'id_elemen' => 89, 'deskripsi_kuk' => 'Peranan yang berbeda dan bagian-bagian dari aplikasi di identifikasi untuk fungsi tertentu.'],
            ['id_kuk' => 277, 'id_elemen' => 89, 'deskripsi_kuk' => 'Aplikasi dioperasikan sesuai dengan prosedur.'],
            ['id_kuk' => 278, 'id_elemen' => 90, 'deskripsi_kuk' => 'File yang akan di akses diidentifikasi sesuai dengan perangkat lunak yang digunakan.'],
            ['id_kuk' => 279, 'id_elemen' => 90, 'deskripsi_kuk' => 'Piranti lunak yang tepat dipilih from menu yang tersedia.'],
            ['id_kuk' => 280, 'id_elemen' => 90, 'deskripsi_kuk' => 'File dapat dikenali untuk dibuka.'],
            ['id_kuk' => 281, 'id_elemen' => 91, 'deskripsi_kuk' => 'Data/informasi yang di akses dipastikan ketepatannya.'],
            ['id_kuk' => 282, 'id_elemen' => 91, 'deskripsi_kuk' => 'Data/informasi yang di unduh disimpan ke dalam file.'],
            ['id_kuk' => 283, 'id_elemen' => 91, 'deskripsi_kuk' => 'Data dicopy sesuai dengan kebutuhan.'],
            ['id_kuk' => 284, 'id_elemen' => 92, 'deskripsi_kuk' => 'Akses peralatan dan sumber daya kerja diidentifikasi untuk menyelesaikan tugas.'],
            ['id_kuk' => 285, 'id_elemen' => 92, 'deskripsi_kuk' => 'Perkiraan jumlah dan sumber daya untuk menyelesaikan tugas dilengkapi.'],
            ['id_kuk' => 286, 'id_elemen' => 92, 'deskripsi_kuk' => 'Peralatan diperiksa untuk pemeliharaan sesuai dengan SOP.'],
            ['id_kuk' => 287, 'id_elemen' => 93, 'deskripsi_kuk' => 'Peralatan dioperasikan sesuai instruksi pada buku petunjuk.'],
            ['id_kuk' => 288, 'id_elemen' => 93, 'deskripsi_kuk' => 'Kerusakan peralatan diidentifikasi secara akurat untuk memastikan perbaikan yang harus diambil sesuai spesifikasi produk.'],
            ['id_kuk' => 289, 'id_elemen' => 93, 'deskripsi_kuk' => 'Perbaikan peralatan yang dilakukan diluar organisasi dilaporkan kepada orang yang tepat sesuai tanggung jawabnya.'],
            ['id_kuk' => 290, 'id_elemen' => 94, 'deskripsi_kuk' => 'Peralatan dan sumber daya untuk mendukung pelaksanaan tugas dipelihara sesuai dengan petunjuk.'],
            ['id_kuk' => 291, 'id_elemen' => 94, 'deskripsi_kuk' => 'Pemeliharaan peralatan dilakukan untuk memastikan bahwa standar pabrik telah terpenuhi.'],
            ['id_kuk' => 292, 'id_elemen' => 94, 'deskripsi_kuk' => 'Pemeliharaan terhadap peralatan dan sumberdaya dicatat sesuai petunjuk.'],
            ['id_kuk' => 293, 'id_elemen' => 95, 'deskripsi_kuk' => 'Perangkat komputer diaktifkan sesuai dengan sistem operasi dan persyaratan manual instalasi.'],
            ['id_kuk' => 294, 'id_elemen' => 95, 'deskripsi_kuk' => 'Piranti lunak untuk membuat surat elektronik dipastikan telah terinstalasi and siap digunakan.'],
            ['id_kuk' => 295, 'id_elemen' => 95, 'deskripsi_kuk' => 'Akun surat elektronik (email) telah dimiliki.'],
            ['id_kuk' => 296, 'id_elemen' => 96, 'deskripsi_kuk' => 'Menu-menu yang disediakan beserta shortcut-nya dikenali berdasarkan user manual sesuai standar tempat kerja.'],
            ['id_kuk' => 297, 'id_elemen' => 96, 'deskripsi_kuk' => 'Format alamat surat elektronik dikenali dan dipahami secara tepat dan cepat.'],
            ['id_kuk' => 298, 'id_elemen' => 96, 'deskripsi_kuk' => 'Konfigurasi sederhana dapat dilakukan sesuai dengan manual yang tersedia.'],
            ['id_kuk' => 299, 'id_elemen' => 97, 'deskripsi_kuk' => 'Surat elektronik baru dapat dibuka dari server menggunakan menu/tombol yang tersedia sesuai SOP organisasi.'],
            ['id_kuk' => 300, 'id_elemen' => 97, 'deskripsi_kuk' => 'Surat elektronik dapat dikenali asalnya dan dapat dibaca isinya dengan baik.'],
            ['id_kuk' => 301, 'id_elemen' => 97, 'deskripsi_kuk' => 'Berkas lampiran (file attachment) dapat diekstrak dari email, secara benar sesuai prosedur.'],
            ['id_kuk' => 302, 'id_elemen' => 97, 'deskripsi_kuk' => 'Surat elektronik dapat diteruskan (forward), dibalas (reply), ke alamat tertentu.'],
            ['id_kuk' => 303, 'id_elemen' => 97, 'deskripsi_kuk' => 'Surat elektronik baru dibuat/ dikomposisi dan dikirim dengan menggunakan fitur yang disediakan.'],
            ['id_kuk' => 304, 'id_elemen' => 97, 'deskripsi_kuk' => 'Pengiriman Surat elektronik dapat dilakukan ke suatu alamat atau beberapa dan dapat disertai dengan file attachment.'],
            ['id_kuk' => 305, 'id_elemen' => 97, 'deskripsi_kuk' => 'Surat elektronik ditulis sesuai dengan memperhatikan netiquette.'],
            ['id_kuk' => 306, 'id_elemen' => 98, 'deskripsi_kuk' => 'Surat elektronik diidentifikasi sehingga secara otomatis dapat masuk ke folder yang telah ditetapkan, secara tepat dan benar'],
            ['id_kuk' => 307, 'id_elemen' => 98, 'deskripsi_kuk' => 'Folder dibuat atau dihapus sesuai kebutuhan'],
            ['id_kuk' => 308, 'id_elemen' => 98, 'deskripsi_kuk' => 'Surat/dokumen elektronik dapat disimpan sesuai media yang tersedia secara tepat.'],
            ['id_kuk' => 309, 'id_elemen' => 99, 'deskripsi_kuk' => 'Peralatan komputer dipastikan telah terhubung dengan internet sesuai SOP organisasi.'],
            ['id_kuk' => 310, 'id_elemen' => 99, 'deskripsi_kuk' => 'Universal reources location (URL) dan homepage ditelusuri secara benar.'],
            ['id_kuk' => 311, 'id_elemen' => 99, 'deskripsi_kuk' => 'Halaman and situs homepage diidentifikasi sesuai kebutuhan.'],
            ['id_kuk' => 312, 'id_elemen' => 100, 'deskripsi_kuk' => 'Informasi terkini diakses sesuai dengan kebutuhan.'],
            ['id_kuk' => 13, 'id_elemen' => 100, 'deskripsi_kuk' => 'Informasi diakses dari sumber yang dapat dipercaya.'],
            ['id_kuk' => 314, 'id_elemen' => 101, 'deskripsi_kuk' => 'Informasi yang diakses pada homepage diidentifikasi secara tepat.'],
            ['id_kuk' => 315, 'id_elemen' => 101, 'deskripsi_kuk' => 'Informasi yang diakses disimpan pada media penyimpanan sesuai kebutuhan.'],
            ['id_kuk' => 316, 'id_elemen' => 101, 'deskripsi_kuk' => 'informasi dipastikan dapat diakses dengan benar sesuai prosedur.'],
            ['id_kuk' => 317, 'id_elemen' => 102, 'deskripsi_kuk' => 'Semua jenis produk perbankan dikenali tujuan dan fungsinya.'],
            ['id_kuk' => 318, 'id_elemen' => 102, 'deskripsi_kuk' => 'Produp perbankan dipilih sesuai dengan kebutuhan perusahaan.'],
            ['id_kuk' => 319, 'id_elemen' => 102, 'deskripsi_kuk' => 'Produk perbankan diidentifikasi sesuai dengan kebutuhan'],
            ['id_kuk' => 320, 'id_elemen' => 103, 'deskripsi_kuk' => 'Transaksi yang akan dilakukan, ditulis dengan jelas pada formulir sesuai kebutuhan.'],
            ['id_kuk' => 321, 'id_elemen' => 103, 'deskripsi_kuk' => 'Pengisian formulir diperiksa ulang ketepatan penulisannya.'],
            ['id_kuk' => 322, 'id_elemen' => 103, 'deskripsi_kuk' => 'Salinan dibuat apabila dibutuhkan.'],
            ['id_kuk' => 323, 'id_elemen' => 104, 'deskripsi_kuk' => 'Transaksi yang sudah dilakukan dicatat dalam pembukuan sesuai dengan SOP.'],
            ['id_kuk' => 324, 'id_elemen' => 104, 'deskripsi_kuk' => 'Bukti-bukti transaksi digandakan untuk disimpan dengan aman.'],
            ['id_kuk' => 325, 'id_elemen' => 105, 'deskripsi_kuk' => 'Dokumen yang akan diarsip dipastikan sudah selesai diproses dan siap untuk disimpan.'],
            ['id_kuk' => 326, 'id_elemen' => 105, 'deskripsi_kuk' => 'Sistem kearsipan diidentifikasi sesuai kebutuhan.'],
            ['id_kuk' => 327, 'id_elemen' => 105, 'deskripsi_kuk' => 'Dokumen diindeks dan ditempatkan sesuai sistem kearsipan yang berlaku dimasing-masing organisasi untuk memudahkan pencarian.'],
            ['id_kuk' => 328, 'id_elemen' => 106, 'deskripsi_kuk' => 'Dokumen disimpan di tempat penyimpanan arsip manual maupun elektronik sesuai sistem yang telah ditentukan.'],
            ['id_kuk' => 329, 'id_elemen' => 106, 'deskripsi_kuk' => 'Pemindahan dokumen dimonitor agar mudah dalam pencarian kembali.'],
            ['id_kuk' => 30, 'id_elemen' => 106, 'deskripsi_kuk' => 'Pemantauan pemeliharaan berkala dilakukan terhadap perlengkapan dan peralatan sesuai dengan buku panduan.'],
            ['id_kuk' => 331, 'id_elemen' => 106, 'deskripsi_kuk' => 'Permohonan perbaikan terhadap perlengkapan/ peralatan yang tidak berfungsi segera dilakukan.'],
            ['id_kuk' => 332, 'id_elemen' => 107, 'deskripsi_kuk' => 'Seluruh dokumen yang telah disahkan oleh pejabat yang berwenang, diidentifikasi sebelum diterbitkan.'],
            ['id_kuk' => 333, 'id_elemen' => 107, 'deskripsi_kuk' => 'Perubahan dokumen dicantumkan revisi.'],
            ['id_kuk' => 334, 'id_elemen' => 107, 'deskripsi_kuk' => 'Dokumen dikendalikan antara dokumen yang dipakai sebagai acuan kerja dengan stempel terkendali atau hanya bahan bacaan dengan stempel tidak terkendali'],
            ['id_kuk' => 335, 'id_elemen' => 107, 'deskripsi_kuk' => 'Unit kerja yang menerima distribusi dokumen ditentukan.'],
            ['id_kuk' => 336, 'id_elemen' => 107, 'deskripsi_kuk' => 'Tanda terima dokumen terkendali dibuatkan dalam bentuk log penerimaan and dikaji secara berkala sesuai ketentuan and disetujui oleh personil yang berwenang'],
            ['id_kuk' => 337, 'id_elemen' => 107, 'deskripsi_kuk' => 'Dokumen yang telah melewati masa simpan ditarik/diambil atau dimusnahkan sesuai ketentuan yang berlaku.'],
            ['id_kuk' => 338, 'id_elemen' => 107, 'deskripsi_kuk' => 'Rekaman dokumen diberi identitas.'],
            ['id_kuk' => 339, 'id_elemen' => 107, 'deskripsi_kuk' => 'Masa simpan atau masa berlaku dari setiap rekaman ditentukan sesuai SOP Organisasi.'],
            ['id_kuk' => 340, 'id_elemen' => 107, 'deskripsi_kuk' => 'Setiap rekaman diperiksa kondisi keutuhannya secara berkala sesuai SOP Organisasi.'],
            ['id_kuk' => 341, 'id_elemen' => 107, 'deskripsi_kuk' => 'Pemantauan pengembalian dokumen yang dipinjam dilaksanakan sesuai SOP Organisasi.'],
            ['id_kuk' => 342, 'id_elemen' => 108, 'deskripsi_kuk' => 'Peralatan dan tempat kerja diidentifikasi.'],
            ['id_kuk' => 343, 'id_elemen' => 108, 'deskripsi_kuk' => 'Seluruh peralatan operasional, diperiksa keamanan dan masa kadaluarsanya sebelum digunakan.'],
            ['id_kuk' => 344, 'id_elemen' => 108, 'deskripsi_kuk' => 'Peralatan kerja yang berhubungan dengan listrik dipastikan keamanannya sesuai SOP.'],
            ['id_kuk' => 345, 'id_elemen' => 108, 'deskripsi_kuk' => 'Peralatan dipergunakan sesuai petunjuk pemakaian.'],
            ['id_kuk' => 346, 'id_elemen' => 108, 'deskripsi_kuk' => 'Pemeliharaan rutin dilakukan sesuai dengan buku petunjuk penggunaan peralatan.'],
            ['id_kuk' => 347, 'id_elemen' => 108, 'deskripsi_kuk' => 'Peralatan disimpan ditempat yang sesuai dengan peraturan penyimpanan dengan kondisi siap pakai.'],
            ['id_kuk' => 348, 'id_elemen' => 108, 'deskripsi_kuk' => 'Kerusakan dilaporkan berdasarkan ketentuan perusahaan.'],
            ['id_kuk' => 349, 'id_elemen' => 108, 'deskripsi_kuk' => 'Perlengkapan keselamatan kerja yang sesuai dikenakan untuk menghindari kecelakaan kerja.'],
            ['id_kuk' => 350, 'id_elemen' => 109, 'deskripsi_kuk' => 'Seluruh peralatan operasional, diperiksa kebersihannya sebelum digunakan.'],
            ['id_kuk' => 351, 'id_elemen' => 109, 'deskripsi_kuk' => 'Peralatan dibersihkan setelah dipakai sesuai dengan buku petunjuk penggunaan peralatan'],
            ['id_kuk' => 352, 'id_elemen' => 109, 'deskripsi_kuk' => 'Bahan-bahan untuk membersihkan disiapkan sesuai dengan petunjuk, persyaratan kesehatan dan keselamatan kerja.'],
            ['id_kuk' => 353, 'id_elemen' => 109, 'deskripsi_kuk' => 'Bahan-bahan kimia disimpan sesuai dengan persyaratan kesehatan dan keselamatan kerja.'],
            ['id_kuk' => 354, 'id_elemen' => 109, 'deskripsi_kuk' => 'Sampah and kelebihan bahan kimia dibuang sesuai higienitas, keamanan serta peraturan mengenai lingkungan'],
            ['id_kuk' => 355, 'id_elemen' => 110, 'deskripsi_kuk' => 'Potensi keadaan darurat diidentifikasi.'],
            ['id_kuk' => 356, 'id_elemen' => 110, 'deskripsi_kuk' => 'Keadaan darurat ditangani sesuai keterampilan yang dimiliki dan kewenangan yang diberikan.'],
            ['id_kuk' => 357, 'id_elemen' => 110, 'deskripsi_kuk' => 'Bantuan dari rekan sejawat atau orang yang berwenang dicari segera, bilamana diperlukan.'],
            ['id_kuk' => 358, 'id_elemen' => 110, 'deskripsi_kuk' => 'Rincian keadaan darurat dilaporkan sesuai dengan aturan.'],
            ['id_kuk' => 359, 'id_elemen' => 111, 'deskripsi_kuk' => 'Tanggap serta pro-aktif terhadap keadaan darurat.'],
            ['id_kuk' => 360, 'id_elemen' => 111, 'deskripsi_kuk' => 'Tindakan dilakukan sesuai keterampilan dan kewenangan yang telah ditentukan dalam menghadapi keadaan darurat, sehingga dapat menentukan langkah langkah selanjutnya.'],
            ['id_kuk' => 361, 'id_elemen' => 111, 'deskripsi_kuk' => 'Fisik korban dan tanda-tanda kehidupan diidentifikasi.'],
            ['id_kuk' => 362, 'id_elemen' => 111, 'deskripsi_kuk' => 'Informasi dan sarana serta prasana layanan pendukung terkini tersedia.'],
            ['id_kuk' => 363, 'id_elemen' => 111, 'deskripsi_kuk' => 'Informasi mengenai kondisi korban disampaikan kepada petugas unit gawat darurat (UGD).'],
            ['id_kuk' => 364, 'id_elemen' => 111, 'deskripsi_kuk' => 'Situasi darurat yang dialami dibakukan dalam bentuk laporan sesuai dengan peraturan.'],
            ['id_kuk' => 365, 'id_elemen' => 111, 'deskripsi_kuk' => 'Laporan dibuat dengan jelas, akurat serta tepat waktu.'],
            ['id_kuk' => 366, 'id_elemen' => 112, 'deskripsi_kuk' => 'Sistem dan prosedur keamanan perusahaan digunakan sesuai dengan SOP Organisasi'],
            ['id_kuk' => 367, 'id_elemen' => 112, 'deskripsi_kuk' => 'Uang kas/tunai disimpan sesuai dengan SOP Organisasi'],
            ['id_kuk' => 368, 'id_elemen' => 112, 'deskripsi_kuk' => 'Perilaku pelanggan yang mencurigakan ditangani sesuai dengan SOP Organisasi'],
            ['id_kuk' => 369, 'id_elemen' => 112, 'deskripsi_kuk' => 'Tindakan pencurian ditangani sesuai dengan SOP Organisasi.'],
            ['id_kuk' => 370, 'id_elemen' => 112, 'deskripsi_kuk' => 'Aset fisik disimpan sesuai SOP Organisasi'],
            ['id_kuk' => 371, 'id_elemen' => 113, 'deskripsi_kuk' => 'Tindakan tepat yang sesuai peraturan dilakukan untuk mengurangi pencurian.'],
            ['id_kuk' => 372, 'id_elemen' => 113, 'deskripsi_kuk' => 'Kode inventaris dicocokkan dengan ketersediaan inventaris secara berkala sesuai peraturan.'],
            ['id_kuk' => 373, 'id_elemen' => 113, 'deskripsi_kuk' => 'Barang yang mudah dicuri diberi pengamanan tambahan sesuai peraturan.'],
            ['id_kuk' => 374, 'id_elemen' => 113, 'deskripsi_kuk' => 'Keamanan staf and pihak luar dijaga sesuai SOP Organisasi'],
            ['id_kuk' => 375, 'id_elemen' => 114, 'deskripsi_kuk' => 'Area kerja ditata sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 376, 'id_elemen' => 114, 'deskripsi_kuk' => 'Tugas rutin dijalankan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 377, 'id_elemen' => 114, 'deskripsi_kuk' => 'Barang-barang diletakkan di area/tempat yang ditunjuk sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 378, 'id_elemen' => 115, 'deskripsi_kuk' => 'Kebijakan dan prosedur gerai mengenai kebersihan pribadi diterapkan pada area kerja.'],
            ['id_kuk' => 379, 'id_elemen' => 115, 'deskripsi_kuk' => 'Pelaksanaan membersihkan area kerja dilaksanakan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 380, 'id_elemen' => 115, 'deskripsi_kuk' => 'Prosedur penanganan sampah gerai dilaksanakan sesuai dengan kebijakan dan peraturan yang relevan.'],
            ['id_kuk' => 381, 'id_elemen' => 115, 'deskripsi_kuk' => 'Tumpahan, tetesan dari makanan, limbah atau zat bahaya lainnya ditangani sesuai dengan persyaratan K3 dan prosedur gerai.'],
            ['id_kuk' => 382, 'id_elemen' => 115, 'deskripsi_kuk' => 'Peralatan dan perlengkapan kerja digunakan sesuai dengan instruksi and aturan penggunaan dari pabrik.'],
            ['id_kuk' => 383, 'id_elemen' => 115, 'deskripsi_kuk' => 'Peralatan dan perlengkapan kerja dibersihkan sesuai dengan instruksi and aturan penggunaan from pabrik.'],
            ['id_kuk' => 384, 'id_elemen' => 115, 'deskripsi_kuk' => 'Peralatan dan perlengkapan kerja disimpan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 385, 'id_elemen' => 116, 'deskripsi_kuk' => 'Tumpahan makanan, limbah atau potensi bahaya lain dilaporkan ke personil yang relevan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 386, 'id_elemen' => 116, 'deskripsi_kuk' => 'Rambu peringatan pada area yang tidak aman dipasang segera.'],
            ['id_kuk' => 387, 'id_elemen' => 116, 'deskripsi_kuk' => 'Alat Pelindung Diri (APD) yang tepat digunakan saat membersihkan area kerja.'],
            ['id_kuk' => 388, 'id_elemen' => 117, 'deskripsi_kuk' => 'Tugas-tugas yang harus diselesaikan diidentifikasi sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 389, 'id_elemen' => 117, 'deskripsi_kuk' => 'Instruksi kerja yang diperlukan untuk menyelesaikan tugas-tugas dicatat sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 390, 'id_elemen' => 117, 'deskripsi_kuk' => 'Kegiatan kerja harian dalam lingkup tanggung jawab direncanakan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 391, 'id_elemen' => 117, 'deskripsi_kuk' => 'Tugas-tugas disusun menjadi bagian yang lebih kecil agar dapat dikerjakan dengan lebih mudah sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 392, 'id_elemen' => 118, 'deskripsi_kuk' => 'Tugas-tugas diurutkan sesuai skala prioritas berdasarkan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 393, 'id_elemen' => 118, 'deskripsi_kuk' => 'Tugas-tugas dilengkapi dengan jadwal yang spesifik dan tuntutan standar dan kualitasnya.'],
            ['id_kuk' => 394, 'id_elemen' => 119, 'deskripsi_kuk' => 'Perubahan-perubahan pada tuntutan kerja diidentifikasi sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 395, 'id_elemen' => 119, 'deskripsi_kuk' => 'Perubahan yang mempengaruhi penyelesaian tugas saat ini dikomunikasikan kepada personil yang relevan.'],
            ['id_kuk' => 396, 'id_elemen' => 120, 'deskripsi_kuk' => 'Peralatan di gerai diidentifikasi sesuai kegunaannya.'],
            ['id_kuk' => 397, 'id_elemen' => 120, 'deskripsi_kuk' => 'Peralatan dipilih berdasarkan jenis pekerjaan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 398, 'id_elemen' => 121, 'deskripsi_kuk' => 'Peralatan dioperasikan sesuai dengan spesifikasi desain dan persyaratan K3.'],
            ['id_kuk' => 399, 'id_elemen' => 121, 'deskripsi_kuk' => 'Kesalahan pada peralatan dilaporkan kepada personil yang relevan.'],
            ['id_kuk' => 400, 'id_elemen' => 122, 'deskripsi_kuk' => 'Program pemeliharaan peralatan diterapkan sesuai kebijakan dan prosedur gerai.'],
            ['id_kuk' => 401, 'id_elemen' => 122, 'deskripsi_kuk' => 'Peralatan disimpan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 402, 'id_elemen' => 123, 'deskripsi_kuk' => 'Persyaratan dan tanggung jawab pekerjaan dilakukan sesuai kebijakan dan prosedur gerai.'],
            ['id_kuk' => 403, 'id_elemen' => 123, 'deskripsi_kuk' => 'Saran diminta from orang yang tepat ketika terjadi ketidaksesuaian pekerjaan dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 404, 'id_elemen' => 123, 'deskripsi_kuk' => 'Ketentuan waktu kerja dilaksanakan sesuai dengan kebijakan dan prosedur perusahaan.'],
            ['id_kuk' => 405, 'id_elemen' => 123, 'deskripsi_kuk' => 'Pengetahuan dan ketrampilan dikembangkan untuk menerapkan hak dan tanggung jawab karyawan maupun perusahaan.'],
            ['id_kuk' => 406, 'id_elemen' => 123, 'deskripsi_kuk' => 'Tugas dan tanggung jawab yang relevan dipatuhi untuk menjaga budaya perusahaan.'],
            ['id_kuk' => 407, 'id_elemen' => 123, 'deskripsi_kuk' => 'Standar dan nilai-nilai yang dapat merugikan perusahaan dikomunikasikan melalui jalur yang telah ditetapkan.'],
            ['id_kuk' => 408, 'id_elemen' => 123, 'deskripsi_kuk' => 'Perilaku yang berkontribusi atas lingkungan kerja yang nyaman, diidentifikasi untuk diterapkan.'],
            ['id_kuk' => 409, 'id_elemen' => 124, 'deskripsi_kuk' => 'Sikap sopan dan suka membantu dalam lingkungan kerja ditunjukkan untuk meningkatkan kinerja tim.'],
            ['id_kuk' => 410, 'id_elemen' => 124, 'deskripsi_kuk' => 'Bantuan kepada rekan kerja diberikan setiap saat sepanjang tidak mengganggu pekerjaan.'],
            ['id_kuk' => 411, 'id_elemen' => 124, 'deskripsi_kuk' => 'Perintah dan tanggung jawab dilaksanakan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 412, 'id_elemen' => 124, 'deskripsi_kuk' => 'Hubungan dengan pelanggan and rekan kerja dijaga agar tidak menimbulkan perselisihan.'],
            ['id_kuk' => 413, 'id_elemen' => 125, 'deskripsi_kuk' => 'Penampilan and cara berpakaian disesuaikan dengan persyaratan di tempat kerja.'],
            ['id_kuk' => 414, 'id_elemen' => 125, 'deskripsi_kuk' => 'Kebersihan pribadi dijaga sesuai kebijakan dan prosedur gerai.'],
            ['id_kuk' => 415, 'id_elemen' => 126, 'deskripsi_kuk' => 'Perintah and prosedur kerja dilaksanakan sesuai ketentuan.'],
            ['id_kuk' => 416, 'id_elemen' => 126, 'deskripsi_kuk' => 'Cara berfikir and bertindak terkait dengan anti-diskriminasi, pelecehan seksual and intimidasi dilakukan sesuai dengan ketentuan hukum yang berlaku.'],
            ['id_kuk' => 417, 'id_elemen' => 126, 'deskripsi_kuk' => 'Pertanyaan diajukan untuk mencari and mengclarifikasi informasi di tempat kerja.'],
            ['id_kuk' => 418, 'id_elemen' => 126, 'deskripsi_kuk' => 'Tugas and pekerjaan rutin sehari-hari diatur sesuai peran kerja.'],
            ['id_kuk' => 419, 'id_elemen' => 126, 'deskripsi_kuk' => 'Tugas-tugas diselesaikan sesuai skala prioritas waktu yang dibuat.'],
            ['id_kuk' => 420, 'id_elemen' => 126, 'deskripsi_kuk' => 'Kepentingan pekerjaan and kepentingan pribadi diidentifikasi untuk mencapai keseimbangan prioritas.'],
            ['id_kuk' => 421, 'id_elemen' => 127, 'deskripsi_kuk' => 'Spesifikasi kemasan and dokumentasi kemasan diidentifikasi.'],
            ['id_kuk' => 422, 'id_elemen' => 127, 'deskripsi_kuk' => 'Jenis-jenis kemasan dipilih sesuai dengan barang-barang yang akan dikemas.'],
            ['id_kuk' => 423, 'id_elemen' => 127, 'deskripsi_kuk' => 'Bahan-bahan kemasan disesuaikan dengan spesifikasi dan kebutuhan.'],
            ['id_kuk' => 424, 'id_elemen' => 127, 'deskripsi_kuk' => 'Pengemasan dilakukan sesuai dengan prosedur and kebijakan gerai.'],
            ['id_kuk' => 425, 'id_elemen' => 127, 'deskripsi_kuk' => 'Bahan-bahan kemasan digunakan secara ekonomis dan tepat, untuk meminimalkan kerusakan dan kerugian pada saat transit atau penyimpanan.'],
            ['id_kuk' => 426, 'id_elemen' => 127, 'deskripsi_kuk' => 'Barang-barang yang telah dikemas, disusun untuk meminimalkan kerusakan dari dalam dan luar.'],
            ['id_kuk' => 427, 'id_elemen' => 128, 'deskripsi_kuk' => 'Standar pemberian label di tempat kerja diidentifikasi sesuai jenis produk.'],
            ['id_kuk' => 428, 'id_elemen' => 128, 'deskripsi_kuk' => 'Pemberian label and simbol dilakukan sesuai dengan standar and kebijakan perusahaan.'],
            ['id_kuk' => 429, 'id_elemen' => 128, 'deskripsi_kuk' => 'Penanganan produk diterapkan sesuai prosedur and kebijakan gerai.'],
            ['id_kuk' => 430, 'id_elemen' => 128, 'deskripsi_kuk' => 'Faktur and slip produk dilampirkan sesuai dengan prosedur gerai.'],
            ['id_kuk' => 431, 'id_elemen' => 128, 'deskripsi_kuk' => 'Dokumentasi dilengkapi sesuai prosedur and kebijakan gerai.'],
            ['id_kuk' => 432, 'id_elemen' => 129, 'deskripsi_kuk' => 'Komunikasi dengan pelanggan yang mencerminkan citra gerai dijaga sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 433, 'id_elemen' => 129, 'deskripsi_kuk' => 'Pelanggan disapa sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 434, 'id_elemen' => 129, 'deskripsi_kuk' => 'Teknik berkomunikasi langsung diterapkan untuk menentukan kebutuhan pelanggan.'],
            ['id_kuk' => 435, 'id_elemen' => 129, 'deskripsi_kuk' => 'Kepercayaan diri and kecekatan dalam bekerja ditunjukkan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 436, 'id_elemen' => 130, 'deskripsi_kuk' => 'Teknik berkomunikasi dengan bantuan teknologi diterapkan sesuai dengan kebijakan dan prosedur gerai.'],
            ['id_kuk' => 437, 'id_elemen' => 130, 'deskripsi_kuk' => 'Email, situs jejaring sosial dan teknologi lainnya digunakan untuk mengolah informasi dan permintaan pelanggan sesuai kebijakan dan prosedur gerai.'],
            ['id_kuk' => 438, 'id_elemen' => 130, 'deskripsi_kuk' => 'Pesan dan informasi disampaikan segera kepada pihak yang terkait.'],
            ['id_kuk' => 439, 'id_elemen' => 130, 'deskripsi_kuk' => 'Masalah dan tindakan relevan yang sedang diambil, diinformasikan kepada pelanggan.'],
            ['id_kuk' => 440, 'id_elemen' => 131, 'deskripsi_kuk' => 'Pelanggan and rekan kerja from latar belakang yang berbeda-beda diperlakukan sama.'],
            ['id_kuk' => 441, 'id_elemen' => 131, 'deskripsi_kuk' => 'Perbedaan budaya dipertimbangkan dalam komunikasi lisan dan tulisan.'],
            ['id_kuk' => 442, 'id_elemen' => 131, 'deskripsi_kuk' => 'Bantuan dimintakan kepada rekan kerja atau atasan, bila diperlukan, untuk memfasilitasi komunikasi.'],
            ['id_kuk' => 443, 'id_elemen' => 132, 'deskripsi_kuk' => 'Bantuan dimintakan kepada anggota tim lainnya saat dibutuhkan.'],
            ['id_kuk' => 444, 'id_elemen' => 132, 'deskripsi_kuk' => 'Jalur komunikasi dengan atasan and rekan kerja dijalankan sesuai kebijakan gerai.'],
            ['id_kuk' => 445, 'id_elemen' => 132, 'deskripsi_kuk' => 'Masukan yang konstruktif from anggota tim lainnya ditindaklanjuti untuk perbaikan kerja tim.'],
            ['id_kuk' => 446, 'id_elemen' => 132, 'deskripsi_kuk' => 'Ketrampilan berkomunikasi ditingkatkan untuk meminimalkan kesalahpahaman.'],
            ['id_kuk' => 447, 'id_elemen' => 132, 'deskripsi_kuk' => 'Komunikasi secara terbuka dan saling menghormati diterapkan untuk menghindari konflik di tempat kerja.'],
            ['id_kuk' => 448, 'id_elemen' => 133, 'deskripsi_kuk' => 'Berbagai macam dokumen ritel dibuatkan daftarnya.'],
            ['id_kuk' => 449, 'id_elemen' => 133, 'deskripsi_kuk' => 'Informasi from berbagai dokumen ritel ditafsirkan untuk diaplikasikan sesuai kebijakan dan prosedur gerai.'],
            ['id_kuk' => 450, 'id_elemen' => 134, 'deskripsi_kuk' => 'Prosedur keselamatan dilakukan untuk mencapai lingkungan kerja yang aman, sesuai dengan peraturan K3 yang relevan, termasuk kode praktek mengenai bahaya tertentu di industri atau tempat kerja.']
        ]);
    }
}