<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitKompetensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('unit_kompetensi')->insert([
            ['id_unit' => 1, 'id_skema' => 1, 'kode_unit' => 'J.59MTM00.010.1', 'judul_unit' => 'Menterjemahkan Arah Visual Ke dalam Langkah Kerja', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan,  keterampilan dan sikap kerja yang dibutuhkan untuk  dapat menterjemahkan arah visual ke dalam langkah kerja.'],
            ['id_unit' => 2, 'id_skema' => 1, 'kode_unit' => 'J.59MTM00.011.1', 'judul_unit' => 'Membuat Aset Visual Berdasarkan Langkah Kerja yang Telah Ditetapkan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk dapat membuat aset visual berdasarkan langkah kerja yang telah ditetapkan'],
            ['id_unit' => 3, 'id_skema' => 1, 'kode_unit' => 'J.59MTM00.027.1', 'judul_unit' => 'Mengumpulkan Asset Multimedia', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk dapat mengumpulkan asset multimedia.'],
            ['id_unit' => 4, 'id_skema' => 1, 'kode_unit' => 'J.59MTM00.028.1', 'judul_unit' => 'Membuat Data Based Multimedia', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk dapat membuat data based multimedia.'],
            ['id_unit' => 5, 'id_skema' => 1, 'kode_unit' => 'J.59MTM00.029.1', 'judul_unit' => 'Mendistribusikan Asset Multimedia', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk dapat mendistribusikan asset multimedia.'],
            ['id_unit' => 6, 'id_skema' => 2, 'kode_unit' => 'J.611000.002.01', 'judul_unit' => 'Mengumpulkan Data Peralatan Jaringann Dengan Teknologi yang Sesuai', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam menentukan teknologi dan perangkat jaringan yang sesuai.'],
            ['id_unit' => 7, 'id_skema' => 2, 'kode_unit' => 'J.611000.003.02', 'judul_unit' => 'Merancang Topologi Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam merancang topologi jaringan komputer.'],
            ['id_unit' => 8, 'id_skema' => 2, 'kode_unit' => 'J.611000.004.01', 'judul_unit' => 'Merancang Pengalamatan Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam merancang pengalamatan jaringan komputer sehingga jaringan bekerja dengan baik.'],
            ['id_unit' => 9, 'id_skema' => 2, 'kode_unit' => 'J.611000.005.02', 'judul_unit' => 'Menentukan Spesifikasi Perangkat Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam menentukan spesifikasi perangkat jaringan.'],
            ['id_unit' => 10, 'id_skema' => 2, 'kode_unit' => 'J.611000.009.02', 'judul_unit' => 'Memasang Kabel Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan memasang kabel jaringan sesuai dengan desain yang telah direncanakan.'],
            ['id_unit' => 11, 'id_skema' => 3, 'kode_unit' => 'J.620100.004.02', 'judul_unit' => 'Menggunakan Struktur Data', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menentukan kompetensi, pengetahuan dan sikap kerja yang diperlukan dalam mempelajari dan membuat struktur data yang akan diterapkan pada pemrograman, tanpa tergantung bahasa pemrograman yang akan dipakai.'],
            ['id_unit' => 12, 'id_skema' => 3, 'kode_unit' => 'J.620100.009.01', 'judul_unit' => 'Menggunakan Spesifikasi Program', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan sikap, pengetahuan, dan keterampilan yang dibutuhkan untuk dapat memahami spesifikasi hasil perancangan program (termasuk Context Diagram (DCD), Data Flow Diagram (DFD), Entity Relationship Diagram (ERD), diagram objek, diagram komponen, class/modul program, properti class, tabel dan deskripsinya) dan menggunakannya.'],
            ['id_unit' => 13, 'id_skema' => 3, 'kode_unit' => 'J.620100.010.01', 'judul_unit' => 'Menerapkan Perintah Eksekusi Bahasa Pemrograman Berbasis Teks, Grafik, dan Multimedia', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan sikap, pengetahuan, dan keterampilan yang dibutuhkan untuk dapat menjalankan code yang dibuat pada lingkungan tools pemrograman tertentu.'],
            ['id_unit' => 14, 'id_skema' => 3, 'kode_unit' => 'J.620100.016.01', 'judul_unit' => 'Menulis Kode dengan Prinsip sesuai Guidelines dan Best Practices', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menentukan kompetensi, pengetahuan dan Sikap kerja yang diperlukan dalam menerapkan prinsip penulisan kode yang baik agar kode tersebut dapat dirawat (maintainability).'],
            ['id_unit' => 15, 'id_skema' => 3, 'kode_unit' => 'J.620100.017.02', 'judul_unit' => 'Mengimplementasikan Pemrograman Terstruktur', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan sikap, pengetahuan, dan keterampilan yang dibutuhkan untuk membuat program terstruktur atau prosedural.'],
            ['id_unit' => 16, 'id_skema' => 3, 'kode_unit' => 'J.620100.023.02', 'judul_unit' => 'Membuat Dokumen Kode Program', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan sikap, pengetahuan, dan keterampilan yang yang diperlukan untuk membuat dokumentasi dari kode program yang telah ditulis secara hardcopy termasuk identifikasi penjelas dari dokumen tersebut.'],
            ['id_unit' => 17, 'id_skema' => 3, 'kode_unit' => 'J.620100.025.02', 'judul_unit' => 'Melakukan Debugging', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan sikap, pengetahuan, dan keterampilan yang dibutuhkan dalam memeriksa kode program dari kesalahan (bug).'],
            ['id_unit' => 18, 'id_skema' => 3, 'kode_unit' => 'J.620100.033.02', 'judul_unit' => 'Melaksanakan Pengujian Unit Program', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan sikap, pengetahuan, dan keterampilan yang dibutuhkan dalam melakukan uji coba unit program.'],
            ['id_unit' => 19, 'id_skema' => 4, 'kode_unit' => 'N.821100.001.02', 'judul_unit' => 'Menangani Penerimaan dan Pengiriman Dokumen/ Surat', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan keterampilan, pengetahuan dan sikap untuk menerima dan mengirimkan surat/dokumen, termasuk surat elektronik.'],
            ['id_unit' => 20, 'id_skema' => 4, 'kode_unit' => 'N.821100.004.02', 'judul_unit' => 'Memproduksi Dokumen', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam memproduksi dokumen.'],
            ['id_unit' => 21, 'id_skema' => 4, 'kode_unit' => 'N.821100.012.01', 'judul_unit' => 'Mengelola Jadwal Kegiatan Pimpinan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam mengelola jadwal kegiatan pimpinan.'],
            ['id_unit' => 22, 'id_skema' => 4, 'kode_unit' => 'N.821100.013.02', 'judul_unit' => 'Mengatur Rapat/Pertemuan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini merupakan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam mengatur rapat/pertemuan.'],
            ['id_unit' => 23, 'id_skema' => 4, 'kode_unit' => 'N.821100.029.02', 'judul_unit' => 'Melakukan Komunikasi melalui Telepon', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berkaitan dengan pengetahuan keterampilan dan sikap kerja yang dibutuhkan dalam melakukan komunikasi melalui telepon.'],
            ['id_unit' => 24, 'id_skema' => 4, 'kode_unit' => 'N.821100.030.02', 'judul_unit' => 'Melakukan Komunikasi Lisan dengan Kolega/Pelanggan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berkaitan dengan pengetahuan keterampilan dan sikap kerja yang dibutuhkan dalam melakukan komunikasi lisan dengan kolega/pelanggan.'],
            ['id_unit' => 25, 'id_skema' => 4, 'kode_unit' => 'N.821100.032.02', 'judul_unit' => 'Melakukan Komunikasi Lisan dalam Bahasa Inggris pada Tingkat Operasional Dasar', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berkaitan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam melakukan komunikasi lisan dalam bahasa Inggris pada tingkat operasional dasar.'],
            ['id_unit' => 26, 'id_skema' => 4, 'kode_unit' => 'N.821100.033.02', 'judul_unit' => 'Membaca dalam Bahasa Inggris pada Tingkat Operasional Dasar', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk membaca dalam bahasa Inggris pada tingkat operasional dasar.'],
            ['id_unit' => 27, 'id_skema' => 4, 'kode_unit' => 'N.821100.034.02', 'judul_unit' => 'Menulis dalam Bahasa Inggris pada Tingkat Operasional Dasar', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk menulis dalam bahasa Inggris pada tingkat operasional dasar.'],
            ['id_unit' => 28, 'id_skema' => 4, 'kode_unit' => 'N.821100.045.02', 'judul_unit' => 'Memberikan Layanan kepada Pelanggan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berkaitan dengan pengetahuan, keterampilan serta sikap kerja yang dibutuhkan dalam memberikan jasa pelayanan kepada pelanggan.'],
            ['id_unit' => 29, 'id_skema' => 4, 'kode_unit' => 'N.821100.053.02', 'judul_unit' => 'Memproduksi Dokumen di Komputer', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam memproduksi dokumen di komputer.'],
            ['id_unit' => 30, 'id_skema' => 4, 'kode_unit' => 'N.821100.054.01', 'judul_unit' => 'Menggunakan Peralatan Komunikasi', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini meliputi pengetahuan, keterampilan dan sikap kerja yang dibutuhkan menggunakan peralatan komunikasi.'],
            ['id_unit' => 31, 'id_skema' => 4, 'kode_unit' => 'N.821100.057.02', 'judul_unit' => 'Mengoperasikan Aplikasi Piranti Lunak', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini meliputi pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk mengoperasikan aplikasi perangkat lunak.'],
            ['id_unit' => 32, 'id_skema' => 4, 'kode_unit' => 'N.821100.058.02', 'judul_unit' => 'Mengakses Data di Komputer', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini meliputi pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk mengakses data di komputer sesuai kebutuhan.'],
            ['id_unit' => 33, 'id_skema' => 4, 'kode_unit' => 'N.821100.059.02', 'judul_unit' => 'Menggunakan Peralatan and Sumber Daya Kerja', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berkaitan dengan pengetahuan, keterampilan and sikap kerja untuk menggunakan peralatan and sumber daya kerja.'],
            ['id_unit' => 34, 'id_skema' => 4, 'kode_unit' => 'N.821100.060.01', 'judul_unit' => 'Membuat Surat/Dokumen Elektronik', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk Membuat surat/dokumen elektronik'],
            ['id_unit' => 35, 'id_skema' => 4, 'kode_unit' => 'N.821100.061.01', 'judul_unit' => 'Mengakses Informasi melalui Homepage', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan untuk mengakses Informasi melalui Homepage.'],
            ['id_unit' => 36, 'id_skema' => 4, 'kode_unit' => 'N.821100.067.01', 'judul_unit' => 'Melakukan Transaksi Perbankan Sederhana', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam melakukan transaksi perbankan sederhana.'],
            ['id_unit' => 37, 'id_skema' => 4, 'kode_unit' => 'N.821100.073.02', 'judul_unit' => 'Mengelola Arsip', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini merupakan kompetensi yang berhubungan dengan pengetahuan, keterampilan, dan sikap kerja dalam mengelola arsip.'],
            ['id_unit' => 38, 'id_skema' => 4, 'kode_unit' => 'N.821100.075.02', 'judul_unit' => 'Menerapkan Prosedur K3 Perkantoran', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini merupakan kompetensi yang berhubungan dengan keterampilan, pengetahuan dan sikap kerja dalam menerapkan prosedur keselamatan dan kesehatan kerja (K3) perkantoran.'],
            ['id_unit' => 39, 'id_skema' => 4, 'kode_unit' => 'N.821100.076.02', 'judul_unit' => 'Meminimalisir Pencurian', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini berkaitan dengan keterampilan, pengetahuan dan sikap yang diperlukan untuk meminimalisir pencurian.'],
            ['id_unit' => 40, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.001.1', 'judul_unit' => 'Merapihkan Area Kerja', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam mengatur and menjaga kerapihan serta kebersihan wilayah kerja sesuai dengan prosedur and kebijakan gerai demi kenyamanan berbelanja pelanggan.'],
            ['id_unit' => 41, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.002.1', 'judul_unit' => 'Menjalankan Tugas and Tanggung Jawab Pribadi', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk mengatur and menyelesaikan tugas pribadi. Kompetensi ini memerlukan kemampuan untuk mengidentifikasi penyelesaian tugas berdasarkan persyaratan kerja and merespon perubahan persyaratan kerja pribadi.'],
            ['id_unit' => 42, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.003.1', 'judul_unit' => 'Mengoperasikan Peralatan Dasar Ritel', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk mengoperasikan berbagai peralatan dasar ritel, mulai dari mengidentifikasi peralatan dasar yang diperlukan, sampai memelihara peralatan ritel untuk meminimalisasi kerusakan.'],
            ['id_unit' => 43, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.004.1', 'judul_unit' => 'Membangun Perilaku Kerja Ritel yang Efektif', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk membangun perilaku kerja ritel secara efektif di dalam lingkungan pelayanan ritel.'],
            ['id_unit' => 44, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.008.1', 'judul_unit' => 'Melakukan Komunikasi Aktif dalam Lingkungan Kerja Ritel', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menjelaskan pengetahaun, keterampilan dan sikap kerja yang diperlukan untuk berkomunikasi efektif dengan pelanggan and staf lain di tempat kerja yang meliputi memilih and menggunakan teknik komunikasi lisan and tulisan secara positif and inklusif serta menafsirkan and menghasilkan informasi tempat kerja dalam berbagai format.'],
            ['id_unit' => 45, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.018.1', 'judul_unit' => 'Menerapkan Perilaku Kerja Aman di Gerai Ritel', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam menerapkan praktek kerja yang aman di lingkungan kerja ritel agar pelanggan merasa nyaman and puas.'],
            ['id_unit' => 46, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.005.1', 'judul_unit' => 'Melakukan Pengemasan Produk', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk mengemas barangbarang sesuai dengan prosedur gerai sebagai bagian dari aktivitas pekerjaan yang dilakukan dalam pengendalian kehilangan dalam industri ritel.'],
            ['id_unit' => 47, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.026.1', 'judul_unit' => 'Membantu Pelaksanaan Perhitungan Stok Barang Dagangan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk berpartisipasi dalam stocktaking, mulai dari persiapan, melakukan stocktaking sampai menyelesaikan perbedaan and selisih demi kelengkapan pembuatan laporan sesuai dengan kebijakan and prosedur gerai.'],
            ['id_unit' => 48, 'id_skema' => 5, 'kode_unit' => 'G.46RIT00.031.1', 'judul_unit' => 'Melakukan Kegiatan Pemajangan Barang Dagangan (Display)', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini menjelaskan pengetahuan, keterampilan dan sikap kerja yang diperlukan untuk menata dan menjaga display sesuai kebijakan dan prosedur gerai guna memenuhi kebutuhan produksi, pengunjung gerai, dan organisasi.'],
            ['id_unit' => 49, 'id_skema' => 6, 'kode_unit' => 'M.692000.001.02', 'judul_unit' => 'Menerapkan Prinsip Praktik Profesional Dalam Bekerja', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berkaitan dengan ketrampilan, pengetahuan dan sikap kerja yang dibutuhkan dalam memahami prosedur, pedoman, kebijakan, dan standar untuk melaksanakan pekerjaan'],
            ['id_unit' => 50, 'id_skema' => 6, 'kode_unit' => 'M.692000.002.02', 'judul_unit' => 'Menerapkan Praktik- Praktik Kesehatan Dan Keselamatan Di Tempat Kerja', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit ini mencakup kompetensi yang berkaitan dengan ketrampilan, pengetahuan, dan sikap kerja yang dibutuhkan dalam menerapkan aspek-aspek kesehatan dan keselamatan di tempat kerja (K3)'],
            ['id_unit' => 51, 'id_skema' => 6, 'kode_unit' => 'M.692000.007.02', 'judul_unit' => 'Memproses Entry Jurnal', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan ketrampilan, pengetahuan dan sikap kerja yang dibutuhkan dalam memproses entri jurnal'],
            ['id_unit' => 52, 'id_skema' => 6, 'kode_unit' => 'M.692000.008.02', 'judul_unit' => 'Memproses Buku Besar', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berkaitan dengan ketrampilan, pengetahuan dan sikap kerja yang dibutuhkan dalam memproses buku besar sesuai dengan prosedur yang ditetapkan pada perusahaan'],
            ['id_unit' => 53, 'id_skema' => 6, 'kode_unit' => 'M.692000.013.02', 'judul_unit' => 'Menyusun Laporan Keuangan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berkaitan dengan ketrampilan, pengetahuan, dan sikap kerja yang dibutuhkan dalam menyusun laporan keuangan akhir periode sesuai dengan ketentuan SOP/SAK/SAK ETAP'],
            ['id_unit' => 54, 'id_skema' => 7, 'kode_unit' => 'M.692000.022.02', 'judul_unit' => 'Mengoperasikan Paket Program Pengolah Angka/Spreadsheet', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berkaitan dengan ketrampilan, pengetahuan, dan sikap kerja yang dibutuhkan dalam mengoperasikan paket program pengolah angka / spreadsheet sesuai dengan prosedur yang ditetapkan pada perusahaan'],
            ['id_unit' => 55, 'id_skema' => 7, 'kode_unit' => 'M.692000.023.02', 'judul_unit' => 'Mengoperasikan Aplikasi Komputer Akuntansi', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berkaitan dengan ketrampilan, pengetahuan dan sikap kerja yang dibutuhkan dalam mengoperasikan aplikasi komputer akuntansi sesuai dengan prosedur yang ditetapkan pada perusahaan'],
            ['id_unit' => 56, 'id_skema' => 8, 'kode_unit' => 'J.611000.001.01', 'judul_unit' => 'Mengumpulkan Kebutuhan Teknis Pengguna yang Menggunakan Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam menentukan kebutuhan teknis pengguna jaringan'],
            ['id_unit' => 57, 'id_skema' => 8, 'kode_unit' => 'J.611000.002.01', 'judul_unit' => 'Mengumpulkan Data Peraiatan Jaringan Dengan Teknologi yang Sesuai', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam menentukan teknologi dan perangkat jaringan yang sesuai'],
            ['id_unit' => 58, 'id_skema' => 8, 'kode_unit' => 'J.611000.008.02', 'judul_unit' => 'Menyiapkan Kabel Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam menyiapkan kabel jaringan komputer dan konektornya serta menguji konektivitasnya pada sistem jaringan'],
            ['id_unit' => 59, 'id_skema' => 8, 'kode_unit' => 'J.611000.009.02', 'judul_unit' => 'Memasang Kabel Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan memasang kabel jaringan sesuai dengan desain yang telah direncanakan'],
            ['id_unit' => 60, 'id_skema' => 9, 'kode_unit' => 'J.611000.005.02', 'judul_unit' => 'Menentukan Spesifikasi Perangkat Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam menentukan spesifikasi perangkat jaringan'],
            ['id_unit' => 61, 'id_skema' => 9, 'kode_unit' => 'J.611000.010.02', 'judul_unit' => 'Memasang Jaringan Nirkabel', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam memasang jaringan nirkabel'],
            ['id_unit' => 62, 'id_skema' => 9, 'kode_unit' => 'J.611000.003.02', 'judul_unit' => 'Merancang Topologi Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam merancang topologi jaringan komputer'],
            ['id_unit' => 63, 'id_skema' => 9, 'kode_unit' => 'J.611000.004.01', 'judul_unit' => 'Merancang Pengaiamatan Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam merancang pengalamatan jaringan komputer sehingga jaringan bekerja dengan baik'],
            ['id_unit' => 64, 'id_skema' => 9, 'kode_unit' => 'J.611000.012.02', 'judul_unit' => 'Mengkonfigurasi Switch pada Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam mengkonfigurasi switch pada jaringan'],
            ['id_unit' => 65, 'id_skema' => 9, 'kode_unit' => 'J.611000.011.02', 'judul_unit' => 'Memasang Perangkat Jaringan ke dalam Sistem Jaringan', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam memasang perangkat jaringan ke dalam sistem jaringan.'],
            ['id_unit' => 66, 'id_skema' => 10, 'kode_unit' => 'J.611000.013.02', 'judul_unit' => 'Mengkonfigurasi Routing pada Perangkat Jaringan dalam Satu Autonomous System', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan dan sikap kerja yang dibutuhkan dalam mengkonfigurasi routing pada perangkat jaringan yang berada pada satu autonomous system menggunakan internal gateway protocol.'],
            ['id_unit' => 67, 'id_skema' => 10, 'kode_unit' => 'J.611000.015.01', 'judul_unit' => 'Memonitor Keamanan and Pengaturan Akun Pengguna dalam Jaringan Komputer', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam memonitor dan mengatur akun pengguna dalam jaringan komputer.'],
            ['id_unit' => 68, 'id_skema' => 10, 'kode_unit' => 'J.611000.023.01', 'judul_unit' => 'Mengganti Perangkat Jaringan Sesuai dengan Kebutuhan Baru', 'standar_kompetensi' => null, 'deskripsi_unit' => 'Unit kompetensi ini berhubungan dengan pengetahuan, keterampilan, dan sikap kerja yang dibutuhkan dalam menganalisis kebutuhan yang disesuaikan dengan peralatan yang dipakai.']
        ]);
    }
}